### ISSUE TITLE
Umsatzsteuer Fahrtkosten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#100]
Die Umsatzsteuer Fahrtkosten lässt sich nicht deaktivieren, auch wenn im Gesamten die Rechnung ohne Umsatzsteuer erstellt wird. Konkret, ich hatte zunächst die Gesamtumsatzsteuer aktiviert, dann deaktiviert, aber bei der Spalte mit den Fahrtkosten bleibt dann der Haken und lässt sich nicht abschalten. Rechnet aber wohl ohne Umsatzsteuer wenn die Gesamtumsatzsteuer abgeschaltet ist, aber der Haken Umsatzsteuer ist immer eingeschaltet....

**Comment by an-mus** [comment]
Der Haken bei der Umsatzsteuer für Auslagen dient nur dazu zu definieren, ob für die Auslagenkategorie generell Umsatzsteuer erhoben wird oder ob die, wie bei den Gerichtskostenvorschüssen genrell nicht anfällt. Wenn du unten den Haken bei der Umsatzsteuer rausnimmst, wird die auch bei den Fahrtkosten nicht berechnet. 
Es ist also nur eine leicht verwirrende Darstellung im Plugin, aber keine Einschränkung der Funktionalität  oder ein Fehler in der Berechnung. Ich würde daher daher darauf verzichten die Funktion zu verändern, da das einen erheblichen Aufwand bedeuten würde und eher die Gefahr beinhaltet, nicht richtige Abrechungen zu erstellen.
