### ISSUE TITLE
RVG Rechner - Taballenformatierung - Unterstreichung

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-calculations#103]
Das Plugin Tabellenformatierung lässt bei Zwischensumme und Zahlbetrag die Option zu Unterstreichungen ab- und anzuwählen. Für die Ergebnisse in den Zeilen Auslagen und Umsatzsteuer gibt es keine solche Option. Die Ergebnisse sind immer unterstrichen.
Ich möchte, bis auf das Feld für die Endsumme (und das am liebsten doppelt) keine Unterstreichungen. Kann man das im Plugin Tabellenformatierung berücksichtigen?

**Comment by an-mus** [comment]
Hi das von dir gewünschte Verhalten bekommst du, wenn den Haken bei "Zahl vor der Summe unterstreichen" wegnimmst und nur den Haken bei Zahlbetrag unterstreichen" lässt.
Ob doppelt unterstrichen geht muss ich noch mal nachschauen.

**Comment by RA-crm** [comment]
Bei mir läuft die 1.0.1. Da gibt es "Zahlbetrag unterstreichen" aber nicht die "Zahl vor der Summe unterstreichen". Wähle ich "Zahlbetrag unterstreichen", dann wird aber nicht nur der eigentliche Betrag, sondern auch das Wort "Zahlbetrag" unterstrichen. Ich hätte gerne nur das Endergebnis unterstrichen
