### ISSUE TITLE
RVG Rechner - Taballenformatierung - Anrechnung

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-calculations#104]
Anrechnungen (zB 1/2 Geschäftsgebühr auf Verfahrensgebühr) sind nichts anderes als Abzüge. Diese stelle ich auf meinen Rechnungen grds. in rot dar. Eine solche Einstellung in der Taballenformatierung wäre gut

**Comment by an-mus** [comment]
Das geht. Werde ich mich die Tage darn machen.

**Comment by stm9x9** [comment]
könnte hier noch ergänzt werden zb: abzüglich anrechenbarer Teil **nach Vorbem. 3 IV**?

**Comment by an-mus** [comment]
Das würde ich nicht ändern. Zumindest bei den Wertgebühren ist nicht nur die Anrechnung nach dieser Vorschrift, sondern auch die nach VV3305 und VV3307 hinterlegt.

**Comment by stm9x9** [comment]
Aber weiß das Plugin nicht, was hier jeweils angerechnet wird, und kann das entsprechend reinschreiben?
