### ISSUE TITLE
RVG Rechner - Taballenformatierung - Linienfarbe

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-calculations#105]
Die Auswahl "Tabellenlinien Farbe" ist zur Zeit fehlerhaft. Linien können nicht in weiß dargestellt werden (Tabellen kopieren und unter Linux (Ubuntu) in Libreoffice 6.0.7.3). Wäre es möglich, auf eine Linierte Umrandung vollständig zu verzichten?

**Comment by an-mus** [comment]
Wenn du den Haken bei "Tabellenlinien einblenden" wegnimmst, sollte es klappen.

**Comment by RA-crm** [comment]
ja, das funktioniert. Klassischer Anwenderfehler. Danke
