### ISSUE TITLE
Plugin Rechner / Löschen-Funktion

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-calculations#108]
In der Löschen-Funktion von einzelnen Zeilen (in den Plugin-Rechnern; ich habe es mit der Honorvereinbarung erprobt) würde ich mir wünschen, dass links in der Übersicht entweder 

- die einzelnen Zeilen sichtbar durchnummeriert sind oder 
- die Zeile, die (durch die Zeilen-Auswahl rechts) gelöscht werden wird, farblich markiert ist
- oder dass bei Markieren der Zeile (und dem dann blauem Hintergrund) rechts die Zeilenangabe automatisch wechselt. 

So wie es aktuell gelöst ist, finde ich das nicht intuitiv und es wird bei einer längeren Liste schnell unübersichtlich. 

![honorar](https://user-images.githubusercontent.com/46451749/83671161-828ab680-a5d4-11ea-9e86-325d5530dc2d.jpg)

**Comment by Dickmaulruessler** [comment]
ah, ich sehe, da ist das schon aufgeführt:
https://github.com/jlawyerorg/j-lawyer-calculations/issues/78

**Comment by j-dimension** [comment]
In der Tat :-)  Dann würde  ich hier schließen. Dein Screenshot ist über die Verlinkung ja verfügbar.
