### ISSUE TITLE
MwST bei der Vorschussanrechnung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#110]
In der Berechnung der Gebühren kann man anwählen, bereits erhaltene Zahlungen anzugeben und die KSW berechnet und weist automatisch den darin enthaltenen MwSt Satz aus.

Wenn man mit der neuen Erweiterung den MwSt Satz auf 16% stellt, weist die KSW bei der Berechnung auch für erhaltene Zahlungen immer nur 16% aus.

Hier müsste eine Wahl eingebaut werden, ob in der erhaltenen Zahlung noch 19% oder schon nur die 16% waren, weil es in den meisten Fällen Vorschüsse mit 19 gewesen sein werden und nächsten Januar in den meisten Fällen dann 16.

**Comment by an-mus** [comment]
Nach den Hinweisen der Brak kommt es wohl nicht darauf an, wann die Vorschüsse gezahlt wurden, sondern welcher Steuersatz für die Schlussrechnung maßgeblich ist.
Trotzdem gibt es Fälle in denen die die Verschiedenen USt Sätze in der ENdabrechnung auftauchen müssen.
Siehe hier: https://www.brak.de/w/files/01_ueber_die_brak/aus-der-arbeit-der-ausschuesse/2020-06-25-umsatzsteuerl.-hinweise-rechnungslegung_erweiterung-ust-absenkung.pdf
