### ISSUE TITLE
Berechnungsplugin übernimmt bei 19% Vorschuss die Eingabe nicht in die Berechnung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#111]
Wenn man bei der Gebührenberechnung aktuell einen 19% Vorschuss eingibt, erscheint in der Berechnung zwar der korrekte MwSt Satz (also der korrekte Betrag der enthaltenen MwSt). Allerdings übernimmt das Plugin den eigentlichen Betrag nicht als Abzugsposten.

Bei dem 16% Vorschuss klappt alles

**Comment by an-mus** [comment]
Ich mache mich später noch an einen Bugfix.
