### ISSUE TITLE
Fehler bei Berechnung ohne Honorar

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#112]
Anwenderin per E-Mail

> Mein Vorgehen: kein Honorar oben eingegeben, da zwei 2 Leistungen (eingegeben unter Sonstiges), dann wollte ich einen Rabatt abziehen - ohne Ust. funktioniert, bei Ust. 19 % wird der Betrag nicht übernommen, klickt man beide USt an, oder nur die 16% wird der Betrag übernommen. Löscht man die Eingaben und klickt auf Berechnen, wird nicht neu berechnet. 

![Unbenannt-1](https://user-images.githubusercontent.com/3729754/86159659-f902d180-bb0a-11ea-99ea-7d7bf12a454c.JPG)
![Unbenannt-2](https://user-images.githubusercontent.com/3729754/86159666-fa33fe80-bb0a-11ea-9d9b-41a3cae8a57c.JPG)
![Unbenannt-3](https://user-images.githubusercontent.com/3729754/86159670-facc9500-bb0a-11ea-9c44-619dcd8aaee3.JPG)

**Comment by an-mus** [comment]
Duplicate of #111
