### ISSUE TITLE
16% MwST werden nicht korrekt berechnet

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#114]
Gestern oder Vorgestern gab es noch eine Grundeinstellung im Menu, in der man die Steuersätze grundsätzlich einstellen konnte. Diese Möglichkeit sehe ich gerade nicht mehr.
Jedenfalls habe ich die Steuersätze aktuell nicht darüber geändert.
Im Berechnungsprogram stelle ich oben auf 16 %, gebe meine Daten ein und das PlugIn berechnet.
Allerdings stehen unten dann zwar 16% da, ausgerechnet werden aber 19%
Erst wenn man die Checkbox vor "Umsatzsteuer VV 7008:" deaktiviert und wieder aktiviert wird mit 16% gerechnet.

**Comment by j-dimension** [comment]
> Gestern oder Vorgestern gab es noch eine Grundeinstellung im Menu, in der man die Steuersätze grundsätzlich einstellen konnte. Diese Möglichkeit sehe ich gerade nicht mehr.

Die Einstellungen wurden der Übersichtlichkeit halber konsolidiert. Siehe https://www.j-lawyer.org/?p=3647

**Comment by an-mus** [comment]
duplicate of #111
