### ISSUE TITLE
Schriftart und -größe für die Tabelle einstellen können

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#115]
Für die Tabelle, die man in die Zwischenablage kopiert, wäre es schön, wenn man die beiden Einstellungen unter Tabelleneigenschaften hätte.
Vielleicht geht das ja umzusetzen.
Herzliche Grüße
Martin

**Comment by j-dimension** [comment]
Wird über https://github.com/jlawyerorg/j-lawyer-org/issues/584 umgesetzt.
