### ISSUE TITLE
Strafrecht: falsche Zwischensumme

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#118]
Von einer Anwenderin:

bei der Berechnung der Gebühren im Strafrecht ist mir ein Bug aufgefallen. Ausgangspunkt: Mandat erst im gerichtlichen Verfahren, bei der Berechnung werden die beiden Terminsgebühren nicht in die Berechnung der Zwischensumme übernommen, nach der die USt berechnet wird - siehe Anhang.

**Comment by j-dimension** [comment]
![image](https://user-images.githubusercontent.com/3729754/88919359-3b830f80-d26b-11ea-8f48-e754fe50b52d.png)

**Comment by PBaumfalk** [comment]
Genau der Fehler ist mir heute nach langer Zeit Strafrecht aufgefallen.

**Comment by an-mus** [comment]
duplicate of #117
