### ISSUE TITLE
BH anrechnen

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#119]
Das Thema war schon mal da #85 und wurde aber geschlossen, weil ich zu spät geantwortet hatte.

Dort wurde darauf verwiesen, dass das Feld "anrechenbarer Teil" editierbar gemacht wird.

Soweit so gut (ich verweise mal auf meine Antwort in #85).

Aber aktuell kann ich das Feld nur editieren, wenn ich die Geschäftsgebühr angehakt habe und diese dann auch in die Berechnung mit einfließt, ansonsten springt das edit Feld immer wieder auf "0". Dann klappt das mit der Anrechnung BH aber leider nicht. Da habe ich ja gerade keine Geschäftsgebühr, die mit berechnet werden soll.

Insofern müsste entweder dieser Bug korrigiert werden oder doch noch mal über meine letzten Ausführungen in #85 nachgedacht werden.

Viele Grüße
Martin

**Comment by an-mus** [comment]
geändert. Das Feld anrechenbarer Teil ist immer frei veränderbar, wenn ein Hacken bei der Checkbox "edit" gesetzt wird.

**Comment by stm9x9** [comment]
irgendwie ist das bei mir gar nichts editierbar?

![image](https://github.com/user-attachments/assets/f40a9804-ceef-4183-bbb4-4ad2479e0fa9)
