### ISSUE TITLE
Formatierung bei Übernahme in Vorlage

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-calculations#120]
Wäre es möglich, wenn die Berechnung bei Einfügen in eine Vorlage über den Platzhalter {{Tabelle_1}} auch die dort gespeicherte Formatierung direkt übernehmen würde? Inklusive Zeilenabstand?

**Comment by iradraconis** [comment]
Gibt es hier einen Trick? Wie handhaben das andere Nutzer? Ich habe noch nicht den Dreh raus. Bei manchen Vorlagen fügt das Plugin eine Tabelle mit Arial in SG 12 ein und manchmal passt die Formatierung so wie sie in der Vorlage vorgegeben ist. Das macht immer wieder extra Arbeit, die Formatierung anzupassen. Vielleicht gibt es einen Kniff, den ich nur noch nicht kenne :)

**Comment by j-dimension** [comment]
Das ist ohne mehr Informationen schwer. Funktioniert es für ein Berechnungsplugin, für ein anderes nicht? Oder ist das abhängig von der Vorlage? Sind die Tabelleneinstellungen entsprechend gesetzt (ist ein eigener Punkt bei den Berechnungen)

**Comment by iradraconis** [comment]
Die Einstellungen in den Tabelleneinstellungen geben mir keine Möglichkeit, die Schriftart und Größe einzustellen. Ich handhabe das so, dass ich in der ODT Vorlage wie gefordert eine Tabelle mit einem Feld und dann den Platzhalter TABELLE_1 einfüge. In der Vorlage wende ich dann die Formatierung Arial 9 an. Wenn jetzt über RVG, zum Beispiel das für OWI/StrR über Dokument erstellen eine Abrechnung erstellt wird, ist in dem erstellten Dokument die Tabelle in Arial 12 und nicht Arial 9.

**Comment by iradraconis** [comment]
Ich muss mich hier noch einmal melden. Es ist wirklich lästig, dass nach Rechnungserstellung bzw. Übernahme einer Berechnung in das Dokument immer wieder die Schriftgröße anpassen muss, weil diese immer in Arial 12 erfolgt. Das führt zu so viel Extra Aufwand bei Rechnungserstellung und Bearbeitung.

Ist das nur bei mir so, also muss ich den Fehler bei mir suchen, oder ist die Übernahme der Formatierung nur noch nicht implementiert? Oder fällt es andernorts nicht auf, weil die Vorlage auch Arial 12 ist?

Edit: zumindest sollte auch bei Übernahme der Berechnung über den kopieren Button in ein bestehendes Dokument die Zielformatierung berücksichtigt werden.

**Comment by j-dimension** [comment]
https://user-images.githubusercontent.com/3729754/171750229-f6d5cf18-c62c-4566-8fd4-c062452ed3a7.mp4

**Comment by iradraconis** [comment]
Großartig, danke Jens!
