### ISSUE TITLE
RVG-Novelle - 01.01.2021

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-calculations#122]
Wir haben die kommende RVG-Novelle auf dem Schirm, oder?

**Comment by j-dimension** [comment]
@PBaumfalk noch nicht so recht. Angeblich soll das zum 01.01. in Kraft treten, korrekt?

Welche konkreten Änderungen gibt es da? Wird es lediglich auf ein Anpassen der RVG-Tabelle hinauslaufen, und die Berechnungen an sich sind weiterhin gültig?

Hier kann evtl. @an-mus mithelfen oder etwas Licht uns Dunkel bringen.

**Comment by PBaumfalk** [comment]
Update: Erstmal ins Backlog. Könnte 2023 werden.
![73958FC9-96D7-4E29-BC37-09E3396D7247](https://user-images.githubusercontent.com/50404378/97434547-71de3280-191f-11eb-91d7-a8bf1c7cdea2.jpeg)

**Comment by j-dimension** [comment]
@PBaumfalk @an-mus nun scheinbar doch zum 01.01.2021. Habt Ihr Einblick was alles an Änderung kommen wird und könnt mir das kurz erläutern?

**Comment by j-dimension** [comment]
https://www.bmjv.de/SharedDocs/Gesetzgebungsverfahren/DE/Justizkostenrecht.html

**Comment by PBaumfalk** [comment]
Bundesrat hat abgelehnt. Wird wohl doch der 1.1.21.

**Comment by an-mus** [comment]
Die Erhöhung ist heute für den 01.01.2021 im Bundestag beschlossen worden. Dann mache ich mich mal ans Werk :-)
Ich denke, dass ich die Änderungen noch im Dezember einpflege.

**Comment by j-dimension** [comment]
@an-mus das wäre grandios!

**Comment by j-dimension** [comment]
Das ist absolute Spitzenklasse, @an-mus ! Hab vielen Dank!

Ich habe noch zwei kleine Commits hinterhergeschoben. Auf den ersten Blick läuft alles wie es soll. Grandios!
