### ISSUE TITLE
[RVG Wertgebühren] - Ausweisen der USt

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-calculations#126]
Das Plugin RVG Wertgebühren wirft Berechnung als Tabellen aus. in der linken Spalte stehen die Gebührensätze. Die Umsatzsteuer steht allerdings im Text der jeweiligen Zeile. Da die Gebührensätze und die Umsatzsteuer jeweils einen Faktor darstellen und weil die Tabelle dann leserlicher ist, schlage ich vor, den Umsatzsteuersatz (5/7/16/19%) aus der Position herauszunehmen und in die erste Spalte linkt zu verschieben. 

![grafik](https://user-images.githubusercontent.com/46541381/101901273-160af880-3bb1-11eb-8069-21627d7b8b8d.png)

**Comment by an-mus** [comment]
geändert.
