### ISSUE TITLE
[FEATURE] Tabelleneinstellung/Standardeinstellung auch für neues RVG

### ISSUE THREAD

**Issue by socram70** [jlawyerorg/j-lawyer-calculations#130]
Eine Option, um den Standardwert für das anzuwendende RVG einzustellen, wäre sehr praktisch (so, wie das schon für die Umsatzsteuer im Screenshot möglich ist).

![grafik](https://user-images.githubusercontent.com/60073801/103905244-aaa83e00-50fe-11eb-913a-7e712f26a040.png)

**Comment by j-dimension** [comment]
Bin unsicher. Das hätte nur einen temporären Nutzwert. Wieviele Berechnungen werden in ein paar Wochen noch nach altem RVG gemacht werden?

Evtl. lieber sicherstellen, dass das neue RVG in allen Berechnern vorausgewählt ist.

**Comment by socram70** [comment]
Stimmt, das ist sogar noch besser. Tatsächlich wird langfristig das alte RVG verschwinden. Allerdings ziehen sich Verfahren ja leider bekanntlich durchaus mal etwas mehr in die Länge. Wegen des § 60 Abs. 1 RVG ist maßgeblich für die Abrechnung, zu welchem Zeitpunkt der Rechtsanwalt beauftragt wurde. In den meisten Fällen, die sich nicht so lange hinziehen, wird aber in der Zukunft das neue RVG angewandt werden.

**Comment by j-dimension** [comment]
rvg, strafrecht, sozialrecht nutzen nun rvg2021 als voreinstellung
