### ISSUE TITLE
RVG Strafrecht Einziehungsgebühr

### ISSUE THREAD

**Issue by LinoPeters** [jlawyerorg/j-lawyer-calculations#132]
Das RVG Plugin Strafrecht sollte um die 

"Verfahrensgebühr bei Einziehung gem. §§ 2, 13 RVG, Nr. 4142 VV RVG"

 erweitert werden.

**Comment by j-dimension** [comment]
@LinoPeters @an-mus wäre das einfach nur ein weiterer Gebühreneintrag unter "allgemeine Gebühren / Vorverfahren"?

**Comment by PBaumfalk** [comment]
1,0 basierend auf dem Wert der Einziehung als Gegenstandswert.

VG
Patrick

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de

BAUMFALK - Rechtsanwaltskanzlei

Hauptkanzlei:
Hauptstr. 195
50169 Kerpen

Zweigstelle:
Berliner Str. 4
58452 Witten

Postanschrift:
Postfach 1233
50141 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by LinoPeters** [comment]
Sehr geehrter Herr Kutschke,
        
        
          wie ich über das System mitgeteilt bekommen habe, sollten wir den 
          Server updaten. Können Sie das für uns vornehmen oder uns mitteilen, 
          was wir dafür tun müssen? Zudem hänge ich an diese Mail wie 
          besprochen zwei Vorlagen an, welche das "Platzhalterproblem" 
          verdeutlichen sollen. In dem Schriftsatz an Mdt. sollte die erste 
          Zeile im Empfängerfeld "Eigene1" (oder so) nur ausgefüllt werden mit 
          einem enstprechenden Inhalt, wenn das Feld genutzt wird. Leider 
          entsteht aber bei leerem Feld eine Freizeile. Dasselbe betrifft den 
          "AkdGrad"im darauffolgenden Schriftsatz an Kollegen: dort etsteht 
          eine Leerfeld zwischen "Herr" und dem Namen des entsprechenden 
          Adressaten. Es geht natürlich, mit relativ wenig Aufwand, die 
          entsprechenden Leerfelder händisch zu löschen aber wir wollen 
          natürlich versuchen von Anfang an möglich wenig manuelle 
          Nachjustierung einzuplanen.
        
        
          Vielen Dank und viele Grüße vom Hamburger Fischmarkt
        
        
          
        
        
          Peters

**Comment by an-mus** [comment]
@j-dimension: bist du da schon dran? Ich würde das sonst die Tage einbauen. Nicht das wir doppelt arbeiten ;-)
@LinoPeters: Die Nr. 4143 bis 4146 sind doch die Gebühren für das Adhäsionsverfahren? Ich in der Uni noch gelernt, dass das praktisch nie vorkommt. Da das aber mittlerweile vielleicht anders ist, würde ich unter "Sonstiges" die Möglichkeit einbauen, Wertgebühren abzurechnen und würde dann gleich alle von 4142 bis 4146 hinzufügen.

**Comment by j-dimension** [comment]
@an-mus nein, bin gerade an anderer Stelle am Schrauben - Deine Hilfe wäre äußerst willkommen!
