### ISSUE TITLE
[RVG Wertgebühren] Fehler bei Einigungsgebühr?

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#133]
Eine Anwenderin hat das Dokument im Anhang zugearbeitet. 

Ist das ein Fehler in unseren Plugins?
[probeabrechnung2.pdf](https://github.com/jlawyerorg/j-lawyer-calculations/files/5921436/probeabrechnung2.pdf)

**Comment by an-mus** [comment]
Das ist ein Duplikat von #47.
Die Rechnung lässt sich umsetzen, indem übersteigende Betrag händisch als Anrechnungsbetrag eingetragen wird. Dazu ist die "edit" Checkbox, um beliebige Anrechnungsbeträge einzutragen (wobei da noch ein Fehler drinsteckt, den ich die Tage beheben werde).
Die andere Frage ist, ob und wie sich diese Deckelung im Hinblick Einigungsgebühren automatisiert berechnen lässt. Ich hätte gedacht, das geht nicht, aber vielleicht ja doch. Dafür fehlt mir schlicht die zivilrechtliche Praxis. Wenn sich die Regelung des § 15 Abs. 3 RVG in der Praxis darauf beschränkt, dass für den Fall, dass eine Einigungsgebühr im Vorverfahren und eine Einigungsgebühr im Gericht auf die 1,5 Gebühr der addierten Streitwerte gedeckelt ist, dann könnten wir das automatisieren. 

Ich könnte das als Entwurf mal umsetzen, der dann aber eine fachliche Überprüfung bräuchte.
@j-dimension: könntest du vielleicht mal meine Mailadresse an die Anwenderin weiterleiten.
@Mucki526: Könntest du da auch noch mal Feedback zu geben?

Ich würde ungern eine automatische Berechnung einbauen, wenn die dann nicht für alle Fälle richtig ist.

**Comment by j-dimension** [comment]
Heute noch evtl. weiteres hilfreiches Feedback von der Anwenderin erhalten: 

Wegen der Kappungsgrenze zwecks Abrechnung von Mehrvergleichen hier noch einmal zur besseren Erläuterung, können Sie evtl. an Ihren Kollegen weiterleiten

Folgender Fall als Beispiel:
Eingeklagt sind 1.000,00 Euro. Im Termin einigt man sich über Ansprüche im Wert von weiteren 1.800,00 Euro. Der Vergleichswert übersteigt den Mehrwert also um 1.800,00 Euro.

Die Verfahrensgebühr
Zunächst wird die Verfahrensgebühr für diese Angelegenheit errechnet. Diese unterteilt sich in die 1.3 Verfahrensgebühr nach RVG VV 3100 über den eingeklagten Betrag (1.000,00 Euro) und in die 0,8 Verfahrensgebühr nach RVG VV 3101 Nr. 2 für den mitverglichenen aber nicht klagegegenständlichen Teil (1.800,00 Euro).
Die Rechnung sieht also so aus:
1,3 Verfahrensgebühr gem. § 13 RVG VV 3100 aus 1.000,00 €	104,00	Euro
0,8 Verfahrensgebühr gem. § 13 RVG VV 3101 Nr. 2 aus 1.800,00 €	120,00	Euro
224,00	Euro
Die Gebührenkappung § 15 Abs. 3 RVG
Im nächsten Schritt wird nun geprüft, ob der Rechtsanwalt durch die Berechnung beider Gebühren nicht mehr erhält, als wäre jeweils die höchste Gebühr entstanden. In diesem Fall wären die Gebühren zu kappen. Und das geht so:
Der höchste Faktor der oben berechneten Verfahrensgebühren ist 1,3. Der Streitwert aus beiden Forderungen beträgt 2.800,00 Euro. Also würde der Gesamtbetrag der nach den Werten berechneten Gebühren wie folgt betragen:
1,3 Verfahrensgebühr gem. § 13 RVG VV 3100 aus 2.800,00 €	261,30	Euro
Wegen § 15 Abs. 3 RVG soll stets der geringere Wert herangezogen werden. Die oben ermittelten einzelnen Gebühren (224,00 Euro) sind nicht höher, als die höchste Gebühr aus der Summe der Streitwerte (261,30 Euro). Deshalb muss nach § 15 Abs. 3 RVG nicht gekappt werden... es bleibt bei den insgesamt 224,00 Euro für die Verfahrensgebühren.

Die Terminsgebühr
Für die Wahrnehmung des Termins muss nun die 1,2 Terminsgebühr nach RVG VV 3104 aus dem Gesamtstreitwert aller streitgegenständlichen - und verhandelten - Gegenstände errechnet werden.
1,2 Terminsgebühr gem. § 13 RVG VV 3104 aus 2.800,00 €	241,20	Euro
Die Einigungsgebühr
Hinsichtlich der Einigung ist wieder zu unterscheiden, ob der Streitgegenstand Teil eines Gerichtsverfahrens war; dann ist die 1,0 Einigungsgebühr des RVG VV 1003 anzusetzen. Für den Teil, bei dem noch kein Gerichtsverfahren anhängig war, fällt die außergerichtliche Einigungsgebühr in Höhe von 1,5 Gebühren nach RVG VV 1000 an. Das sieht dann so aus:
1,0 Einigungsgebühr gem. § 13 RVG VV 1003 aus 1.000,00 €	80,00	Euro
1,5 Einigungsgebühr gem. § 13 RVG VV 1000 aus 1.800,00 €	225,00	Euro
305,00	Euro
Noch einmal Gebührenkappung
Auch bei dieser Gebühr fallen zwei unterschiedlich hohe Teilgebühren an, so dass wir wieder prüfen müssen, ob die Kappungsgrenze des § 15 Abs. 3 RVG erreicht ist. Der höhere Faktor ist hier die 1,5. Der Gesamtstreitwert beträgt wieder 2.800,00 Euro.
1,5 Einigungsgebühr aus 2.800,00 €	301,50	Euro
Diesmal beträgt die Summe aus den einzelnen Beträgen 305,00 Euro und die Gebühr aus dem Gesamtbetrag 301,50 Euro. Nach der Grundregel den § 15 Abs. 3 RVG: "Im Zweifel den niedrigeren Wert nehmen" dürfen hier also maximal 301,50 € abgerechnet werden. Die Abrechnung der Einigungsgebühr nach Gebührenkappung müsste also so aussehen:
1,0 Einigungsgebühr gem. § 13 RVG VV 1003 aus 1.000,00 €	80,00	Euro
1,5 Einigungsgebühr gem. § 13 RVG VV 1000 aus 1.800,00 € Gebührenkappung nach § 15 Abs. 3 RVG	221,50	Euro
301,50	Euro

**Comment by j-dimension** [comment]
> könntest du vielleicht mal meine Mailadresse an die Anwenderin weiterleiten.

@an-mus wollen wir das andersherum machen? Ich würde die Anwenderin mal fragen, ob ich ihre Kontaktdaten an Dich weitergeben darf?

**Comment by Mucki526** [comment]
Die dargestellte Anrechnungsmethode und Deckelung ist richtig, habe nie verstanden, warum das nicht gehen soll und es freut mich, wenn das umgesetzt wird. Eigentlich ist es relativ einfach darzustellen und oft gelebter Standard im Zivilrecht. Es sind Sonderfälle denkbar, z.B. dass die Terminsgebühr nur aus dem geringeren Wert des gerichtlichen Verfahrens anfällt, aber das ist ja kein Problem, weil man ja die Streitwerte bei jeder Gebühr anpassen kann.

**Comment by an-mus** [comment]
> @an-mus wollen wir das andersherum machen? Ich würde die Anwenderin mal fragen, ob ich ihre Kontaktdaten an Dich weitergeben darf?

Mach das gerne.

**Comment by an-mus** [comment]
@Mucki526 : Ich habe die Deckelung nach § 15 Abs. 3  jetzt mal umgesetzt. Das waren doch etwas aufwändigere Änderungen. Es wäre super, wenn du die Funktion ausführlich testen könntest. 
Ich habe jetzt auch den Fall einbezogen, dass der Mehrvergleich erst in der 2. Instanz zustande kommt. Ich hoffe das ist richtig. 
Hinsichtlich der Darstellung nachher im Dokument war ich unsicher. Ich habs jetzt einfach mal als Abzug wie in der Beispielrechnung gemacht. Wenn da noch andere Vorschläge hast, sag Bescheid.
Schöne Grüße
A

**Comment by Maz111111** [comment]
Deckelung der Einigungsgebühr scheint nicht zu funktionieren.

  | Position | Betrag
-- | -- | --
  |   |  
1,3 | Verfahrensgebühr Nr. 3100 VV RVG - 31.298,00 € | 1.219,40 €
1,2 | Terminsgebühr Nr. 3104 VV RVG - 47.318,00 € | 1.395,60 €
1,0 | Einigungsgebühr Nr. 1003 VV RVG - 3.300,00 € | 252,00 €
  | Auslagen Nr. 7002 VV RVG | 20,00 €
1,5 | Einigungsgebühr Nr. 1003f VV RVG - 16.020,00 € | 1.044,00 €
0,8 | Verfahrensgebühr Nr. 3101 VV RVG - 16.020,00 € | 556,80 €
  | abzüglich Deckelung nach §15 Abs. 3 RVG - Verfahrensgebühr | -264,30 €
  |   |  
  | Zwischensumme | 4.223,50 €
19 % | Umsatzsteuer Nr. 7008 VV RVG | 802,46 €
  |   |  
  | Zahlbetrag | 5.025,96 €

Außerdem sollte bei der Einigungsgebühr unter sonstige Wertgebühren 1,5 vorgegeben werden, da dies m.E. der häufigste Anwendungsfall ist

Auch dürfte das f hinter der 1003 bei der Einigung unter sonstige Gebühren vertippt sein.

Schön wäre auch, wenn man die Verfahrens und die Einigungsgebühren jeweils direkt untereinander darstellen könnte

Liebe Grüße
Martin

**Comment by an-mus** [comment]
Hallo Martin,
an die Beschriftung muss ich noch mal ran.
Die Lösung für deine Rechnung ist, die 1,5er Gebühr nicht über die sonstigen Wertgebühren, sondern über den Eintrag "Einigungsgebühr" unter "Vorverfahren" einzubeziehen. Da ist sie auch richtig als 1,5er und mit der Beschriftung VV1000 ausgewiesen und wird in die Deckelung mit einberechnet.
Der Nachteil ist dann, dass die dann in der exportierten Tabelle vorne steht, dass kann ich aber auch noch mal ändern.

**Comment by Maz111111** [comment]
Ok das macht Sinn.

Ich hätte eine Anmerkung über die man vielleicht nachdenken kann.

eine Deckelung ist ja eigentlich kein Abzugsposten, sondern eine Begrenzung.

Wäre es nicht systematisch richtiger und für den Rechnungsempfänger auch verständlicher, wenn man anstatt eines für den Leser nicht nachvollziehbaren Abzugsposten, den Höchstwert darstellt ("die Einigungen dürfen nicht mit mehr abgerechnet werden als mit einer 1,5er aus dem Gesamtwert aller Einigungen") und diesen dann ggf. anwendet ("alle Einigungen insgesamt daher: xxxx Euro"). Für die Verfahrensgebühr analog.

Herzliche Grüße
Martin

**Comment by an-mus** [comment]
https://github.com/jlawyerorg/j-lawyer-calculations/commit/7c293ea561de5493bcb049613f870c838fbd88a2
