### ISSUE TITLE
BUG: Rechner RVG Wertgebühren kann Berechnungen ab 2.000.001 EUR Gegenstandswert nicht durchführen

### ISSUE THREAD

**Issue by jphaag** [jlawyerorg/j-lawyer-calculations#135]
Im konkreten Fall: 2.250.000 Streitwert.

**Comment by j-dimension** [comment]
Angeber :-)

Ich habe RVG 2021 jetzt bis 3 Mio erweitert. Nach einem Neustart des Clients ist das bereits nutzbar.

**Comment by jphaag** [comment]
👍 ;)
