### ISSUE TITLE
Mehrvergleich scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#137]
Es wurde VKH 19% MwST und neue Gebühren gewählt.
Die Deckelung für die Verfahrensgebühr passt
Für die Einigungsgebühr kommen falsche Zahlen.

<html>

  | Position | Betrag
-- | -- | --
  |   |  
1,3 | Verfahrensgebühr Nr. 3100 VV RVG - 4.000,00 € | 361,40 €
1,2 | Terminsgebühr Nr. 3104 VV RVG - 6.000,00 € | 354,00 €
1,0 | Einigungsgebühr Nr. 1003 VV RVG - 4.000,00 € | 278,00 €
  | Auslagen Nr. 7002 VV RVG | 20,00 €
0,8 | Verfahrensgebühr Nr. 3101 VV RVG - 2.000,00 € | 132,80 €
1,5 | Einigungsgebühr Nr. 1003f VV RVG - 2.000,00 € | 249,00 €
  | abzüglich Deckelung nach §15 Abs. 3 RVG - Verfahrensgebühr | -110,70 €
  | abzüglich Deckelung nach §15 Abs. 3 RVG - Einigungsgebühr | -2,50 €
  |   |  
  | Zwischensumme | 1.282,00 €
19 % | Umsatzsteuer Nr. 7008 VV RVG | 243,58 €
  |   |  
  | Zahlbetrag | 1.525,58 €

</html>

**Comment by an-mus** [comment]
Hi,
ich konnte auf die schnelle deine Rechnung hier nicht reproduzieren. Komisch. 
Aber versuch doch mal die 1,5 Einigungsgebühr nicht über die "sonstigen Wertgebühren" sondern über die Einigungsgebühr unter "Vorverfahren" einzugeben. Im Moment rechnet das plugin die Abhängigkeiten zwischen den Einigungsgebühren nur zwischen denen, die du unter Vorverfahren, 1. Instanz und 2. Instanz auswählen kannst. Einigungsgebühren, die du unter sonstige Wertgebühren eingeben kannst werden bisher ignoriert.
Wäre das sinnvoll die noch zu ergänzen?

**Comment by Maz111111** [comment]
Ich denke das wäre sinnvoll.
Ich wüsste nicht, wo ich die 1,5er Einigung sonst platzieren sollte bzw. warum sie ins Vorverfahren oder die 1. bzw. 2 Instanz gehören sollte.
Zumal es mit der 0,8er bei den sonstigen Wertgebühren ja klappt. Da halte ich es für logisch, dass auch die andere Mehrvergleichsgebühr über sonstige einzugeben ist.
Viele Grüße

**Comment by an-mus** [comment]
https://github.com/jlawyerorg/j-lawyer-calculations/commit/7c293ea561de5493bcb049613f870c838fbd88a2
