### ISSUE TITLE
Anwender: Eintragung des Datums bei der Terminsabrechnung ist nicht möglich

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#142]
@LinoPeters

**Comment by an-mus** [comment]
Es ist möglich, hinter dem Begriff "Terminsgebühr" weiteren Text zu ergänzen (z.B. das Datum). Wenn du dann auf Hinzufügen klickst, wird der Text in die Abrechnung mit übernommen.
