### ISSUE TITLE
[FEATURE] RVG-Rechner um Mahnbescheid erweitern

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-calculations#143]
RVG-Rechner zwischen Vorverfahren und 1. Instanz um Mahnbescheid erweitern.

**Comment by PBaumfalk** [comment]
Ja. Das wäre geil!

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   ***@***.***


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: ***@***.***
Web: www.kanzlei-baumfalk.de

Sent by Mobile
