### ISSUE TITLE
Mehrere Terminsgebühren im Vorverfahren in Abrechnungsmodul Strafrecht/Owi

### ISSUE THREAD

**Issue by MarcoWolny** [jlawyerorg/j-lawyer-calculations#145]
Es kommt gerade im Strafrecht häufig vor, dass mehrere Termine im Vorverfahren stattfinden. So heute wieder: Zuführung zum Haftrichter am 24.12., Haftprüfung heute. Beide Gebühren entstehen im Vorverfahren, wo das Plugin - anders als in den Instanzen - keine weitere Terminsgebühr vorsieht. 

Kann gelöst werden, indem auch im Vorverfahren die Terminsgebühr als Dropdown mit "Hinzufügen"-Button eingegeben wird.

**Comment by stm9x9** [comment]
Mit der Lösung ist die Terminsgebühr aber in der Tabelle dann nicht mehr im jeweiligen Verfahrensabschnitt. :-( Könnte man das entweder durch so eine Liste je Abschnitt machen oder aber doch so, daß nach Hinzufügen das im Abschnitt verbleibt und eine neue Zeile für einen möglichen weiteren Termin hinzugefügt wird? Und dann noch einen und noch einen, wenn man immer wieder draufklickt?

**Comment by an-mus** [comment]
Die Terminsgebühren werden bei der Ausgabe ins Dokument oder in die Zwischenablage wieder korrekt den jeweiligen Instanzen zusortiert.
