### ISSUE TITLE
Umsatzsteuer in Zahlbetrag angeben

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-calculations#146]
Wenn man im Rechner Honorarvereinbarung eine Summe ausrechnen läßt und davon dann wieder geleistete Zahlungen mit USt abziehen läßt, dann steht unten nur der Zahlbetrag aber nicht die darin noch enthaltene USt. Kann man sich zwar aus der Zeile Umsatzsteuer und der Erläuterung "darin enthaltene USt. (19 %): xxx €" ausrechnen als Kunde, aber schöner wäre es, wenn ganz unten stünde "Zahlbetrag (darin enthaltene USt. xxxx €"

![image](https://user-images.githubusercontent.com/29924198/168496762-156f0185-f2f9-4762-aed7-03f6346b7fbf.png)

Das dürfte auch für die anderen Rechner gelten.

**Comment by stm9x9** [comment]
Da ist noch ein Rechenfehler drin, aber ich komme leider nicht drauf, wieso.

![image](https://github.com/user-attachments/assets/149d095d-fbb3-4f3e-bb37-e57fdec50098)

Oder doch, ich glaube, er rechnet für die noch enthaltene USt immer mit 19% (bzw. dem %-Satz der endgültigen Rechnung) statt mit dem Satz der konkreten Zeile:

![image](https://github.com/user-attachments/assets/9330db5b-653f-4565-97df-64f7b46cc666)

hier müßten es 140,22 - 16 = 124,22 sein. Oder habe ich da einen Denkfehler?

**Comment by an-mus** [comment]
Inhalt der Änderung ist, dass in der Fußzeile nochmal die Umsatzsteuer im verbleibenden Zahlbetrag ausgewiesen wird. Und diese Rechnung ist richtig.  

Die Beispielrechnung von dir betraf den Fall, dass du ein Mandat zu einem Zeitpunkt abrechnest, als 19% abzuführen war, du aber schon Vorschüssen zu 16% vereinnahmt hattest. Wie man das genau darstellt, habe ich erfolgreich wieder verdrängt. Ich meine, es gab da mal umfangreiche Erklärtexte der BRAK zu.  Da aber wahrscheinlich niemand mehr so alte Abrechnungen mehr hat, ist das doch eher eine akademische Frage für Steuerberater*innen.
Ich frage mich eher, wann ein guter Zeitpunkt ist, die Erfassung der Zahlungen zu  16% wieder raus zu werfen...

**Comment by an-mus** [comment]
Und klar die Summenbildung der kann nicht aufgehen. Du musstest auf den Gesamtbetrag die Umsatzsteuer zum Zeitpunkt der Rechnungsstellung ausweisen und du musstest die jeweilige Umsatzsteuer auf die einzelnen Vorschusszahlungen ausweisen, die dann aber ja teilweise nur 16% war.

**Comment by j-dimension** [comment]
> Ich frage mich eher, wann ein guter Zeitpunkt ist, die Erfassung der Zahlungen zu 16% wieder raus zu werfen...

👍

**Comment by stm9x9** [comment]
> Du musstest auf den Gesamtbetrag die Umsatzsteuer zum Zeitpunkt der Rechnungsstellung ausweisen und du musstest die jeweilige Umsatzsteuer auf die einzelnen Vorschusszahlungen ausweisen, die dann aber ja teilweise nur 16% war.

Die im Gesamtbetrag enthaltene Umsatzssteuer steht ja schon weiter oben als VV RVG 7008. Unten steht nur noch der übrige Zahlbetrag. Und da ist die enthaltene Steuer aktuell falsch. Mit der Zahlung der 116 sind 16 € Steuer gezahlt worden und von allen verbucht und angemeldet worden.

Aufgrund der Schlußrechnung steht fest, es sind auf den gesamten Betrag 19% mithin 140,22 zu zahlen. Von denen wurden bereits 16 gezahlt, also ist an Steuer noch 124,22 offen. Da steht aber 121,70

**Comment by stm9x9** [comment]
> Da aber wahrscheinlich niemand mehr so alte Abrechnungen mehr hat, ist das doch eher eine akademische Frage für Steuerberater*innen.
> Ich frage mich eher, wann ein guter Zeitpunkt ist, die Erfassung der Zahlungen zu 16% wieder raus zu werfen...

Das werden wir, genauso wie RVG 2013 noch eine ganze Weile benötigen.

Wenn ich in zwei Jahren in zweiter Instanz vor dem hoffnungslos überlasteten LSG gewonnen haben werde, dann muß ich gegenüber dem Gegner das in 2020 mit 16% zu versteuernde Widerspruchsverfahren sowie das mit 19% zu versteuernde Klageverfahren ab 2021 abzurechnen haben. Und wenn es vor das BSG geht ... 

Genauso wenn man vor dem OLG die Klage aus 2021 gewinnt und das vorgerichtliche Mahnverfahren aus 2020 mitabrechnen muß ...   

Und was die USt bei Vorschüssen angeht: Wenn ich hoffentlich Anfang 2025 die eine Klage aus 2020 vor dem SG(!) nur teils gewinne und PKH abrechnen muß, dann muß da auch der Vorschuß mit 16% mir rein.
