### ISSUE TITLE
RVG Strafrecht: Wahlverteidigergebühren

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#149]
Anwender:

"Und zwar fehlt im RVG Strafrecht Plugin die Möglichkeit, sog. „Wahlverteidigergebühren“ um mehr als 20% gegenüber der Mittelgebühr zu erhöhen (oder zu reduzieren)."

**Comment by an-mus** [comment]
Das funktioniert schon. Das Menü ist mit "Mittelgebühr" bzw. "Mitelg." beschriftet. Du kannst entweder oben unter "pauschale Erhöhung/Reduzierung" alle Gebührentatbestände um 10% oder 20% erhöhen oder reduzieren oder bei jedem Tatbestand einzeln.

**Comment by iradraconis** [comment]
"Eigene" auswählen und die Gebühr individuell eintragen
