### ISSUE TITLE
Abrechnungsmöglichkeit auf Honorarbasis / Stunden

### ISSUE THREAD

**Issue by Dickmaulruessler** [jlawyerorg/j-lawyer-calculations#15]

**Comment by j-dimension** [comment]
Frage: das wäre ein neues Plugin, korrekt?

**Comment by Dickmaulruessler** [comment]
ja

**Comment by j-dimension** [comment]
#31 aus Core-Repo hierher transferiert - Feature wird dort weitergeführt. Schliesse dieses hier als Duplikat und registriere @Dickmaulruessler am anderen Ticket als Beobachter.
