### ISSUE TITLE
Rechnungsnummern werden in unlesbaren Zeichen kopiert.

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-calculations#150]
Rechnungsnummern werden in unlesbaren Zeichen kopiert.

**Comment by j-dimension** [comment]
Passiert das immer oder sporadisch?
War es schon immer so, oder ist es erst jetzt aufgetreten?

**Comment by j-dimension** [comment]
> Passiert das immer oder sporadisch?
> War es schon immer so, oder ist es erst jetzt aufgetreten?

@PBaumfalk Ticket gern wieder aufmachen, wenn es noch Input gibt - danke!
