### ISSUE TITLE
Plugin „Rechner RVG Wertgebühren“ keine Deckelung nach § 15 Abs. 3 – Einigungsgebühr

### ISSUE THREAD

**Issue by DenisLug** [jlawyerorg/j-lawyer-calculations#159]
**Describe the bug / Fehlerbeschreibung**

Beim Plugin „Rechner RVG Wertgebühren“ wird die Deckelung nach § 15 Abs.  3 – Einigungsgebühr nicht vorgenommen.

**To Reproduce / Schritte zum Nachvollziehen**
1.	Gehe zu „Rechner RVG Wertgebühren“
2.	Gebe z.B. Gegenstandswert von 20.000 EUR an
3.	Klicke bei 1. Instanz auf 1,0-Einigungsgebühr VV1003f. 
4.	Gebe bei „sonstigen Wertgebühren“ eine weitere „Einigungsgebühr Nr. 1003 f. VV RVG“
•	Gegenstandswert: z.B. 30.000 EUR
•	1,5-Einigungsgebühr
5.	Klicke weiter unten auf „Deckelung nach § 15 Abs. 3 – Einigungsgebühr“
6.	Es findet keine Deckelung statt.

**Expected behavior / Erwartetes Verhalten**

Es müsste eine Deckelung auf eine 1,5-Einigungsgebühr auf den addierten Wert der Einigungsgebühren (50.000) EUR erfolgen. Also auf 1.918,50 EUR netto.

Da keine Deckelung stattfindet, werden fehlerhaft 986,40 EUR + 1.432,50 EUR = 2.418,90 EUR angesetzt.
Es hätte eine Deckelung erfolgen müssen.

**Screenshots**
![Plugin Deckelung nach § 15 Abs   3 – Einigungsgebühr](https://github.com/jlawyerorg/j-lawyer-calculations/assets/17670072/c62d1f4e-d428-4e2b-92bd-817e526437be)

**Environment / verwendete Umgebung:**
•	OS / Betriebssystem: MacOS
•	J-lawyer.org Version: 2.5.0.0
•	Letzte Aktualisierung des Plugins: 18.01.2024

**Comment by an-mus** [comment]
https://github.com/jlawyerorg/j-lawyer-calculations/commit/7c293ea561de5493bcb049613f870c838fbd88a2
