### ISSUE TITLE
Featurewunsch: Hebegebühr 1009 RVG als weitere Wertgebühr

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-calculations#160]
![2024-07-31 10 51 37](https://github.com/user-attachments/assets/eac95cf3-109e-4c09-b19a-89157e0002ca)

**Comment by iradraconis** [comment]
Hebegebühr ist drin, aber ohne Berechnung, müsste m.E. zu den Wertgebühren mit Berechnung. Wäre toll.

**Comment by an-mus** [comment]
Da ist schon eine Berechnung hinterlegt, die zugegebenermaßen nicht ins Auge springt. Du kannst unter "Anzahl" den Betrag eingeben, aus dem die Hebegebür gezogen werden soll. Das Plugin berechnet dann die Gebühr.

**Comment by an-mus** [comment]
Wenn das für deine Bedürfnisse funktioniert, sag noch mal Bescheid. Ansonsten würde ich das Ticket schließen.

**Comment by iradraconis** [comment]
Klasse! Aber da wäre ich selbst nicht drauf gekommen. Das würde mir so reichen, da ich jetzt weiß, wie es geht :)

**Comment by Dickmaulruessler** [comment]
> Klasse! Aber da wäre ich selbst nicht drauf gekommen. Das würde mir so reichen, da ich jetzt weiß, wie es geht :)

Off-topic: Hilf' mal bitte kurz, wann kann man die Gebühr berechnen?

**Comment by stm9x9** [comment]
> Off-topic: Hilf' mal bitte kurz, wann kann man die Gebühr berechnen?

wenn man als Anwalt für den Mandanten (vereinbarungsgemäß) Geld entgegennimmt.
