### ISSUE TITLE
Sonstige Gebühren (anders) sortieren / benennen

### ISSUE THREAD

**Issue by stm9x9** [jlawyerorg/j-lawyer-calculations#163]
Aktuell sind die sonstigen Gebühren lose gruppiert aber nicht erkennbar sortiert:

![image](https://github.com/user-attachments/assets/cdb9890d-2294-4a70-9153-0b8e30caf988)

Könnte man die mit ihrer VV-Nummer voranbenennen (so es denn eine gibt) und dann nach dieser sortieren? Als Anwälte sind wir es IMHO gewohnt in diesen Nummern zu denken.

Also:

1009 VV RVG Hebegebühr
7000 VV RVG Kopien s/w
7000 VV RVG Kopien farbig
7000 VV RVG elektronische Datei
7001 VV RVG Post/TK-Auslagen
7005 VV RVG Tagesgeld bis 4h
7005 VV RVG Tagesgeld 4 bis 8h
...
Auslage Gebühr Akteneinsicht
sonstige Auslagen steuerpflichtig (netto)
sonstige Auslagen umsatzsteuerfrei

**Comment by stm9x9** [comment]
Was ich dabei nicht bedacht habe, die übrigen Positionen sind ja (noch) andersrum und mit Nr. benannt:

![image](https://github.com/user-attachments/assets/96e0963f-fd0d-4487-ba80-c867d1b49be2)

Könnte man das noch anpassen und die Nr. dazufügen?

**Comment by stm9x9** [comment]
hier ist das dann auch nochmal wieder anders in der Plugin-Oberfläche mit VV vorne und ohne Leerzeichen:

![image](https://github.com/user-attachments/assets/a397f305-4429-4102-9e85-7d51cabd4bd6)

oder im Strafrecht teils vorne mit Nr. aber ohne VV, teils mit.

![image](https://github.com/user-attachments/assets/bd312ec9-b0ff-4d42-aa4e-02b3a15706a6)

**Comment by stm9x9** [comment]
und wenn man das dann noch auch im Output umstellen würde, wie hier in Zeile 1 als Beispiel gemacht, dann könnte man die Angabe des Streitwerts "beschreibender" hinschreiben statt mit "-" mit einem "...gebühr aus ..."

![image](https://github.com/user-attachments/assets/e0c5b152-b0a0-4b4a-b2ed-0ff4f2012400)

**Comment by an-mus** [comment]
Ich würde die Änderungen bei den sonstigen gebühren wieder rückgängig machen.
Ansonsten ist doch so, dass in der Programmoberfläche nur knapp der Name der Gebühr und die Nummer VVxxxx benannt ist. Damit ist die Oberfläche eindeutig und sehr übersichtlich beschriftet. 
Die Ausgabe sieht dann ja eh noch mal anders aus. Da gibt es glaube ich sehr viele unterschiedliche Geschmäcker und ziemlich sicher keine Version, die alle Anwender*innen zufriedenstellen wird.

Bei Strafrechts/Owig Plugin liegt die Sache nochmal anders. Da das eigentlich vier Plugins in einem sind, (Wahlverteidigung, Pflichtverteidigung, jeweils für Strafrecht und Owis), muss die gesamte Beschriftung des Plugins dynamisch verändert werden. Bei den aus den Auswahlboxen übernommenen Gebühren muss die Beschriftung direkt aus der Pluginoberfläche genommen werden, weswegen da leider die komplette Beschriftung ("Nr. RVG") mit ins Plugin musste. Da das aus meines Sicht funktional keine Einschränkung hat würde ich da nicht weiter dran gehen.

**Comment by stm9x9** [comment]
ich meinte zum einen den Unterschied hier:

![image](https://github.com/user-attachments/assets/dd59fac4-87f9-414d-bc33-f88cf9a18b97)

Und grundsätzlich die Nr vor den Text zu setzen, also Nr. 2300 VV RVG Geschäftsgebühr halte ich einfach fürs Auge besser, weil die Nummer damit immer an derselben Stelle stehen, aktuell ist das sehr unruhig optisch:

![image](https://github.com/user-attachments/assets/2bbf5239-aa39-4792-b1ec-4b0241e2ace1)
