### ISSUE TITLE
Sozialrecht: Trennung zwischen normaler Gebühr und Erhöhungsprozenten

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#20]
Trennung zwischen normaler Gebühr und Erhöhungsprozenten bei mehreren Mandanten wäre nett

**Comment by an-mus** [comment]
Ich  gehe mal davon aus, dass das ein Duplikat zu #9 ist. Ich hatte dort zumindet schon mal was zur Darstellung der Gebührenerhöhung für mehere Mandanten geschrieben bzw. warum die jetzige Darstellung vorzugswürdig ist.
