### ISSUE TITLE
Strafrecht:  Haftzuschlag

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#21]
ich weiß es gerade nicht: Mandant ist nur während vor oder nur während der HV i nHaft: Haftzuschlag für alle Gebühren und Zeiträume?

https://www.j-lawyer.org/?p=2682

**Comment by an-mus** [comment]
stimmt, der Haftzuschlag muss für alle Gebühren einzeln auswählbar sein, wenn der Mandant nicht für das ganze Verfahren in Haft ist
