### ISSUE TITLE
Strafrecht: VV 7002

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#22]
ich weiß es gerade nicht: gehört zur GG nicht auch noch eine AuslagenG VV 7002?

https://www.j-lawyer.org/?p=2682

**Comment by an-mus** [comment]
Zur Grundgebühr gehört keine Auslagenpauschale (VV 7002). Die Auslagenpauschale entsteht in jeder Instanz, auch im Vorverfahren (vgl. § 17 Nr. 10 a RVG). Insofern entspricht die Darstellung im Plugin dem RVG.
