### ISSUE TITLE
RVG-Rechner: Prozessgebühr / Einigungsgebühr

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#27]
Es fehlt im Rechner noch die erhöhte Prozessgebühr bei einem Mehrwert der Einigung 0,8 Gebühr 3101 VVRVG und eine 1,5 Einigungsgebühr bei einem Mehrwert der Einigung über nicht rechtshängige Ansprüche sowie die zugehörige Höchstbetragsrechnung nach 15 RVG...

**Comment by an-mus** [comment]
Die Gebühr 3101 ist jetzt bei den benutzerdefinierten Wertgebühren verfügbar. 
Bei der "1,5 Einigungsgebühr .." must du mir mal auf die sprünge helfen.

**Comment by an-mus** [comment]
Duplikat von #47
