### ISSUE TITLE
RVG-Rechner: Variante Erstellen in Dokument - es fehlen die Währungsangaben in der Ergebnistabelle

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#28]
Das Kürzel {{TABELLE_1}}, das zum Einfügen der Tabelle sein soll funktioniert bei mir nicht ....

**Comment by j-dimension** [comment]
Der Platzhalter muss in einer eine Zelle großen Tabelle enthalten sein - Beispiel siehe Dokumentation: 
http://www.j-lawyer.org/downloads/documentation/j-lawyer.org-UserGuide-de.pdf

**Comment by Mucki526** [comment]
Ah.... alles klar. Danke! Wenn nichts mehr hilft, lesen wir die Anleitung :-)....

**Comment by Mucki526** [comment]
Jetzt geht es grundsätzlich und wenn ich aus dem Plugin das dokument erstelle gibt es auch die Leerzeilen nicht (nur bei kopieren und einfügen erscheinen die...). Aber jetzt habe ich keine Währung hinter den berechneten Zahlen. Ist das ein Fehler im Plugin oder sitzt der Fehler hinter der Tastatur???

**Comment by j-dimension** [comment]
In der Tat ein Fehler. Ich mache das Ticket wieder auf, mit anderem Namen.
