### ISSUE TITLE
RVG - Gegenstandswert

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#29]
Es fehlt die Möglichkeit unterschiedliche Gegenstandswerte bei unterschiedlichen Gebühren einzustellen. Wenn z.B. nur ein Teil einer Forderung eingeklagt wird, hat die Verfahrensgebühr einen niederen Gegenstandswert. Wenn die Einigung bei einer Scheidung nur über den Versorgungsausgleich geht, hat sie einen niederen Gegenstandswert als die Verfahrensgebühr. Wenn z.B. sich vor dem Termin ein Teil der Forderung erledigt, hat die Terminsgebühr und Einigungsgebühr einen niedrigeren Gegenstandswert. Vielleicht wäre es eine Idee, die Auswahl eines Gebührentatbestandes durch eine Klappleiste möglich zu machen, in der beim Tatbestand der Gegenstandswert, die Gebühr (0,3, 0,5 - 2,5 etc.) auswählbar ist (soweit gesetzlich vorgesehen und die Zeile dann eingefügt wird in die Tabelle...?. (Die Tabelle sollte nach dem Export in Libre Office zudem verschiebar und formatierbar sein, kommt sicher noch...).

**Comment by j-dimension** [comment]
> Die Tabelle sollte nach dem Export in Libre Office zudem verschiebar und formatierbar sein

In LibreOffice hat man doch alle Möglichkeiten die LO bietet - was genau möchtest Du erreichen?

**Comment by Mucki526** [comment]
Ich kann in Libre office die importierte Tabelle (Kopie - Paste, (weil der Platzhalter für Einfügen der Tabelle nicht funktioniert) nicht formatieren (Zeilenbreite, Buchstabengröße).... Vielleicht mein Fehler, sonst ist das kein Problem...

**Comment by Mucki526** [comment]
Konkret - die Buchstaben in der Tabelle lassen sich problem formatieren, aber die Zeilenhöhe läßt sich nicht kleiner machen weder mit Maus noch mit  "Größe" in Libreoffice  Ich würde gerne die Tabelle unten anfassen können und einfach schmaler ziehen, wenn die letzte Zeile z.B. mit der Summe nicht mehr auf die Seite passt... Könnte natürlich eine grundsätzliche Sache von Libreoffice Writer sein.

**Comment by j-dimension** [comment]
Ich kann das weder mit LO5 noch mit LO6 nachvollziehen.

- Buchstabengröße: gewünschte Inhalte markieren, Schriftgröße ändern
- Zeilenbreite: die Linien der Tabelle anfassen und ziehen
- Zeilenhöhe: ebenfalls über die Linien der Tabelle. Die Zeilenhöhe reduziert sich auch automatisch, wenn man eine kleinere Schriftgröße vergibt

Ggf. schauen wir mal zusammen drauf.

**Comment by an-mus** [comment]
Alle Gegenstandswerte sind einzelne einstellbar.
https://github.com/jlawyerorg/j-lawyer-calculations/commit/0182b21f84f3d5a932bd0f5d302a4249feaf7742
