### ISSUE TITLE
RVG Umsatzsteuer

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#30]
Es fehlt die Möglichkeit, einen anderen Mehrwertsteuersatz (7% z.B. bei Fährenbenutzung) auszuwählen.

**Comment by an-mus** [comment]
Ich hatte auch erst gedacht das das notwendig ist, ist es aber nicht. Die korrekte Abrechnung ist im Plugin umgesetzt. Es müssen die Netto Fartkosten angesetzt werden, auf die dann einheitlich 19% MwSt. aufgeschlagen werden. Die anteiligen 7% MwSt auf Nahverkehr, Taxi, Fähre etc. dürfen wir nicht an den Kostenschuldner weiterreichen. Das führt dazu, dass sich für den Kostenschuldner die MwSt. erhöht. Für uns ist das egal, weil es ein durchlaufender Posten ist. Vgl. KG Berlin: https://www.burhoff.de/asp_weitere_beschluesse/inhalte/2348.htm
