### ISSUE TITLE
Darstellung der RVG Rechnung als Tabelle

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-calculations#32]
In der Tabelle der RVG Rechnung ist eine Spalte für den Faktoren der Wertgebühr und der Umsatzsteuer aufzunehmen.

**Comment by an-mus** [comment]
Die Faktoren der Wertgebühren tauchen jetzt in der Tabelle auf, jedoch ohne eine eigene Spalte.
