### ISSUE TITLE
Zurücksetzen bei benutzerdefiniert

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#34]
Bei Benutzerdefiniertem Gebühreneintrag (RVG-Rechner) werden mit "Zurücksetzen" das ganze Feld gelehrt. Blöd, wenn nur eine Zeile falsch ist und man alles nochmal eingeben muss (mehrere Zeilen). Ein Löschen einer Einzelzeile ist nicht möglich. Ein Markieren einer Zeile und zurücksetzen löscht auch alle Einträge.

**Comment by Mucki526** [comment]
Sinnvoll wäre - zurücksetzen löscht die Eingabezeile und den Betrag. Die einzelnen Eingaben sind editierbar und löschbar - in der Luxusausführung ist zudem die markierte Position verschiebbar (z.B. mit Strg - Pfeil).

**Comment by an-mus** [comment]
An dem Problem bin ich dran. Mir schwebt vor, den "Zurücksetzen" Botton zu entfernen und einen Button einzufügen, mit dem einzelne Zeilen gelöscht werden können. 
Maus-Aktionen (z.B Rechtsklick -> ausgewählte Zeile löschen) übersteigt leider meine Programmierfähigkeiten :-)

**Comment by j-dimension** [comment]
@an-mus, gib bescheid wenn Hilfe benötigt wird. Klappt dann aber erst nach meinem Urlaub.
