### ISSUE TITLE
Benutzerdefinierter Gebührenbestand

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#36]
Es wird keine Mehrwertsteuer berechnet aus benutzerdefinierten Gebühren. Vorschlag - Button vor jede manuelle Gebühr um Umsatzsteuer auswählen zu können, da manche individuelle Gebühren 0 (ÖPNV), manche 7 (Fähre), manche 19 % USt haben.

**Comment by an-mus** [comment]
erledigt. Auf die benutzerdefinierten Einträge werden jetzt auch 19% Mehrwehrtsteuer aufgeschlagen (sofern die Umsatzsteuer berechnet werden soll).
7% Umsatzsteuer brauchen wir meines Wissens nicht. Ich hatte an anderer Stelle schon mal geschrieben:

Ich hatte auch erst gedacht das das notwendig ist, ist es aber nicht. Die korrekte Abrechnung ist im Plugin umgesetzt. Es müssen die Netto Fahrtkosten angesetzt werden, auf die dann einheitlich 19% MwSt. aufgeschlagen werden. Die anteiligen 7% MwSt auf Nahverkehr, Taxi, Fähre etc. dürfen wir nicht an den Kostenschuldner weiterreichen. Das führt dazu, dass sich für den Kostenschuldner die MwSt. erhöht. Für uns ist das egal, weil es ein durchlaufender Posten ist. Vgl. KG Berlin: https://www.burhoff.de/asp_weitere_beschluesse/inhalte/2348.htm
