### ISSUE TITLE
Kostennote über RVG-Plugin - Auswahl Adressat geht nicht

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#37]
Wenn ich mit dem RVG-Plugin die Gebühren berechnen lasse und in ein Dokument einfügen will (als über den Platzhalter), dann die Akte auswähle, wird richtig die Möglichkeit zum Auswählen einer Vorlage geöffnet, aber ich habe rechts keinen Eintrag mehr unter Mandant, Gegner, Dritter und kann daher auch nichts auswählen. Das Dokument läßt sich erstellen, aber die Anschrift fehlt naturgemäß mangels Auswahl vorher.

Wenn ich die gleiche Akte und die gleich Vorlage nehme und einfach das Dokument direkt aus dem Hauptprogramm erstelle, wird auch die Möglichkeit zum Auswählen einer Vorlage geöffnet, aber ich kann ganz normal Mandanten, Gegner, Dritte auswählen und das Dokument wird erstellt (natürlich ohne Berechnung).

**Comment by j-dimension** [comment]
Ist bereits von einem anderen Anwender gemeldet worden, wird mit 1.10 geliefert.
