### ISSUE TITLE
Bezeichnung Zahlbetrag

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#38]
Ich würde den Zahlbetrag am Ende der Berechnung nicht Summe nennen, sondern Zahlbetrag. Zumindest sollte es imho (irgendwann) die Möglichkeit geben, diesen frei umzubenennen.

**Comment by j-dimension** [comment]
Frei umbenennen könnte man es direkt im Dokument.
@an-mus, was meinst Du zur generellen Umbenennung?

**Comment by Mucki526** [comment]
Na wenn ich das Modul aufrufe, dass jedesmal Zahlbetrag drinsteht und ich nicht jedesmal editieren muss. Das Tolle am Computer ist ja die Automatisierung von Problemem, die man ohne Computer nicht hätte ;-). Kurz, die Bezeichungen im Plugin editieren können.
