### ISSUE TITLE
Unterstreichungen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#39]
Ich fände es gut, wenn bei Export der RVG Berechnung in ein Dokument die Zahlen über den Zwischensummen bzw. dem Zahlbetrag unterstrichen wären oder dies möglich wäre.

**Comment by an-mus** [comment]
Hängt hiervon ab: https://github.com/jlawyerorg/j-lawyer-org/issues/188

**Comment by j-dimension** [comment]
https://github.com/jlawyerorg/j-lawyer-org/issues/188 ist umgesetzt, die Pluginanpassungen können erst ab Veröffentlichung j-lawyer.org 1.11 vorgenommen werden.

**Comment by j-dimension** [comment]
Bsp.: 

https://github.com/jlawyerorg/j-lawyer-calculations/blob/master/src/1.11.0.0/rvg_ui.groovy
