### ISSUE TITLE
RVG: flexible Eingabe beliebiger eigener Kostentatbestände

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#4]

**Comment by j-dimension** [comment]
@an-mus um Input gebeten

**Comment by j-dimension** [comment]
Kommentar von @Mucki526 an Ticket #41 

> Es wäre eine Ergänzung, wenn man in der freien Auswahl auch zum Gegenstandswert Gerichtskosten (1x, 2x oder 3x, je nach Fall) auswählen und einfügen könnte. Wir stellen oft dem Mandanten auch Gerichtskostenvorschüsse in Rechnung....). Ohne "Schuss" kein "Jus"....

**Comment by an-mus** [comment]
Ich habe mir den Code für die benutzerdefinierten Einträge mal angeschaut und ich glaube, damit kommen wir gut weiter. Ich habe testweise angefangen Berechnungen zu hinterlegen.
Als nächstes würde ich die ganzen Auslagen (Kopien, Fahrtkosten, Tagegeld, ...) verschieben. Damit lassen sich #10, #23 und #24 schließen. Ich hoffe, das Plugin wird damit übersichtlicher. Gleichzeitig ist das eine gute Lösung, wenn einzelne Gebühren mehrfach anfallen.
Zusätzlich würde ich eine zweite Zeile einfügen, in der beliebige Faktoren gegen den Streitwert gerechnet werden. Damit können wir auch "exotischere" Tatbestände aufnehmen (#27). 

Ich mache mich da beizeiten dran.

**Comment by j-dimension** [comment]
@an-mus hab 1000 Dank vorab! Mir ist noch nicht ganz klar inwieweit die benutzerdefinierten Einträge mit Faktoren und USt. ineinandergreifen müssen / sollen.

Wenn Du Hilfe brauchst oder ich diesen Umbau irgendwie unterstützen kann - wir können auch gern mal telefonieren.

**Comment by an-mus** [comment]
Benutzerdefinierte Kostentatbestände eingebaut. Für Wertgebühren udn Auslagen.
https://github.com/jlawyerorg/j-lawyer-calculations/commit/0182b21f84f3d5a932bd0f5d302a4249feaf7742
