### ISSUE TITLE
Auslagenpauschale Nr. 7000 VV RVG aufnehmen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#40]
Bei den außergerichtlichen Gebühren die Auslagenpauschale Nr. 7000 VV RVg aufnehmen

**Comment by j-dimension** [comment]
@RasimT

**Comment by an-mus** [comment]
Duplikat von https://github.com/jlawyerorg/j-lawyer-calculations/issues/14
