### ISSUE TITLE
Gerichskosten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#41]
Es wäre eine Ergänzung, wenn man in der freien Auswahl auch zum Gegenstandswert Gerichtskosten (1x, 2x oder 3x, je nach Fall) auswählen und einfügen könnte. Wir stellen oft dem Mandanten auch Gerichtskostenvorschüsse in Rechnung....). Ohne "Schuss" kein "Jus"....

**Comment by j-dimension** [comment]
Ich habe das am Ticket #4 kommentiert und schliesse dieses hier als Duplikat.
