### ISSUE TITLE
Grenzen Gegenstandswert

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#44]
Höchtmöglicher Gegenstandswert von 500.000 € ist in Scheidungsverfahren und vielen Erbrechtsangelegenheiten zu niedrig. Über 500.000 € wirft das Plugin negative Werte für die Gebühren aus.

**Comment by j-dimension** [comment]
Ich habe eine Tabelle gefunden die bis 1Mio geht. Würde das reichen bzw. kennst Du eine Quelle die für größere Beträge?

**Comment by Mucki526** [comment]
Die Gebühren werden berechnet, irgendwelche Tabellen sind davon nur abgeleitet:
I.) Anleitung für die Berechnung § 13 RVG
https://www.gesetze-im-internet.de/rvg/__13.html
Rundungsvorschrift: §2RVG ...
II.) (2) Gebühren werden auf den nächstliegenden Cent auf- oder abgerundet; 0,5 Cent werden aufgerundet.
III.) Höchstwerte: § 22 RVG
Höchstbeträge hat der Gesetzgeber leider vorgesehen (30 Mio /100 Mio Gegenstandswert), Großkanzleien können sich daran stoßen, ich noch nicht - leider
https://dejure.org/gesetze/RVG/22.html
Ich denke das ist besser als eine Tabelle, die das nicht ganz abdeckt. Muss halt bei einer Gebührenerhöhung (das passiert leider nur alle 10 Jahre mal..., das letzte Mal vor 6 Jahren) angepasst werden.
