### ISSUE TITLE
Rechnung aus plugin erstellen

### ISSUE THREAD

**Issue by Hohenhorst** [jlawyerorg/j-lawyer-calculations#45]
Wenn ich versuche, aus dem Berechnungsprogramm eine Rechnung zu erzeugen (Dokument erstellen), erscheint in der Auswahl der Vorlage der Mandant nicht. 
![grafik](https://user-images.githubusercontent.com/36954899/51998414-e79e3b80-24b8-11e9-8f6e-efeb8c0fb81f.png)
Dementsprechend kann ich keinen Mandanten einwählen, und die Prozedur endet mit der Fehlermeldung
![grafik](https://user-images.githubusercontent.com/36954899/51998470-06043700-24b9-11e9-91e6-c1a4a110ca4a.png)
Wliegt der Fehler?

**Comment by j-dimension** [comment]
Der Fehler liegt in der Software :-)

Das Problem ist bekannt und als Ticket #222 bereits im Entwicklungsstand für j-lawyer.org 1.10 behoben. 

Und es gibt auch für 1.9.1 Abhilfe: Statt die Berechnung über das Hauptmenü zu starten, bitte mal über den Tab "Schäden" einer Akte die Berechnung starten - dort gibt es das Problem nicht.

Ich schliesse daher das Ticket als Duplikat von #222.

**Comment by j-dimension** [comment]
Siehe https://github.com/jlawyerorg/j-lawyer-org/issues/222
