### ISSUE TITLE
Anrechenbarer Anteil RVG Vers. 1.91

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#46]
Der anrechenbare Anteil kann nicht höher sein als die Hälfte der gerichtlichen Gebühr. Streitwert Verfahrensgebühr 2.000 € - Streitwert für anrechenbarer Anteil maximal 2.000 €. Anders gesagt, wenn der außergerichtliche Streitwert 4.000 € beträgt und gerichtlich sich nur mit 1.000 € deckt, wird die Anrechnung auch nur aus 1.000 € berechnet, selbst wenn der Verfahrenswert für das gerichtliche Verfahren z.B. 20.000 € sein sollte. 
Die Anrechnung sollte daher sinnvollerweise auch eine variable Streitwerteingabe bekommen, da es keinen Automatismus dahingehend gibt, welcher Teilwert des außergerichtlichen Verfahrens Gegenstand der Klage ist und welche nicht.

**Comment by an-mus** [comment]
Die Anrechnung aus dem Vorverfahren hat erstmal keinen variablen Streitwert bekommen, da m.e. alle notwendigen Werte vorliegen. Jetzt wird die Anrechnung mit dem Streitwert aus der VV3100 Gebühr gerechnet (falls dieser höher ist) und der Faktor auf 0,75 gedeckelt.
@Mucki526 : schau doch mal ob es so richtig ist.

**Comment by Mucki526** [comment]
Nein, leider ist das nicht so einfach, denn dann wäre es nicht Jura sondern Fußball..... Ich spreche jetzt mal nur für die normalen Geschäftsgebühr 2300 und Verfahrensgebühr 3100. 

Erste Erkenntnis 

Die Geschäftsgebühr RVG 2300 hat einen eigenen Gegenstandswert. Die Klage (Verfahrensgebühr 3100 hat einen eigenen Gegenstandswert). Die Schnittmenge für die Anrechnung muss nicht die Differenz aus beiden sein. Also muss man für die Anrechnung einen eigenen Streitwert eingeben können müssen. Genau genommen müsste man aus einer Drop-Down-Liste den jeweiligen RVG Tatbestand auswählen und den Gegenstandswert (wenn Gegenstandswertabhängig). 

Zweite Erkenntnis

Die Anrechnung erfolgt nur aus dem Wert der Schnittmenge, höchstens somit aus dem Wert des Klageverfahrens. Vorbemerkung 3 Abs. 4 S. 5 VVRVG.  Also Bsp.: Außergerichtlich 5.000 € GWert, davon Gerichtlich 1.000 € eingeklagt, dann Anrechnung 0,65 aus 1.000,00.  ... 2. Beispiel: Außerg. 5.000 GW, Gerichtlich 1.000,- aber nur 500,- € Schnittmenge - Anrechnung nur 0,65 aus 500,-. 3. Beispiel Außgerichtlich 1.000 €, Eingeklagt 5.000 €, Anrechnung wenn Gegenstand außergerichtlich vollständig in Klage enthalten maximal 0,65 € aus 1.000.

Dritte Erkenntnis: Eine Anrechnung erfolgt maximal in Höhe der angefallenen Verfahrensgebühr. Wenn z.B. nur eine 0,5 Gebühr angefallen ist (z.B. Anmeldung Forderung zum Insolvenzverfahren) und eine 1,3 Geschäftsgebühr angefallen ist, dann nur maximal Anrechnung 0,5 Gebühr (immer nur soweit gleiche Angelegenheit)

Vierte Erkenntnis.: Die Erhöhungsgebühr fällt an, wenn man mehrere Auftraggeber bzgl. des gleichen Gegenstands vertritt. Es ist auch denkbar, dass man mehrere Auftraggeber erst im Klageverfahren hat und außergerichtlich zuvor aber nur einen der Mandanten vertreten hat, weil der andere zuvor außergerichtlich selbst rumgewurstelt hatte. Also Erhöhung erst im Klageverfahren.

Fünfte Erkenntnis: Wenn man unterschiedliche Aufträge z.B. zweier Gesellschafter annimmt und in einer Klage geltend macht (für Gesellschafter A Forderung 10.000 € und für Gesellschafter B 10.000 €, dann gibt es wegen unterschiedlicher Gegenstände (Forderung A nicht gleich Forderung B) keine Erhöhungsgebühr für mehrere Auftraggeber, sondern eer Streitwert sind 10.000 € + 10.000 €.

Sechste Erkenntnis:

Erhöhung und Anrechnung daher nur, wenn es sich um die gleiche Angelegenheit handet. Anrechnung auch aus der Erhöhung für mehrere Auftraggeber, weil die Erhöhung keine eigene Gebühr ist, sondern die Grundgebühr erhöht wird. Anrechnung im Verfahren aber höchstens mit 0,75. 

Siebte Erkenntnis:

Es gibt Fälle, da trete in einem Verfahren mehrere Geschäftsgebühren auf oder/und es treten mehrere Verfahrensgebühren auf (z.B. wenn sich durch Zahlung ein Teil der Forderung nach Klageauftrag aber vor Klageerhebung erledigt.) Eine weitere Verfahrensgebühr ist aber auch die 0,8 Verfahrensgebühr, die man erhält, wenn man andere Ansprüche die nicht Gegenstand der Klage sind mit erledigt. (Dann aber Deckelung beachten § 15 Abs. 3 RVG) 

Wenn sowas programmiert wird, könnte folgendes Buch hilfreich sein (ich sitze gerade davor...) (wenn man Zeit und Lust hat, sich mit dem RVG auseinanderzusetzen (Horst Enders RVG für Anfänger (mit vielen Beispielen ISBN 978 3 406 67869 1)). Löst 95% aller Fragen...

**Comment by an-mus** [comment]
Du hast recht. Der Faktor und der Gegenstandswert können jetzt frei eingestellt werden.
