### ISSUE TITLE
Fehlende Möglichkeit für Erledigung nichtrechtshängiger Ansprüche im Verfahren.

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#47]
Es gibt besondere Gebühren für die Erledigung nicht rechtshängiger Ansprüche in einem gerichtlichen Verfahren. A und B streiten sich über das grüne Auto vor Gericht, Wert 5.000 €. Daneben haben sie einen Streit über ein Motorrad, Streit bisher nur außergerichtlich, Wert Motorrad 2.000 €. Sie erledigen den grüne Autostreit und den Streit über das Motorrad vor Gericht. Dann wird wie folgt abgerechnet:

1,3 Verfahrensgebühr gem. 3100 VVRVG aus 5.000 €
0,8 Gebühr gem. 3101 VVRVG aus 2.000,00 € (erhöhte Prozessgebühr), jedoch nicht mehr als eine 1,3 Gebühr aus (5.000,- + 2.000,- = 7.000 €). Deckelung nach 15 III RVG
1,3 Terminsgebühr aus 7.000 € (kann man ja dann auswählen)
1,0 Einigungsgebühr aus 5.000 €
1,5 Einigungsgebühr aus 2.000 €
jedoch nicht mehr als eine 1,5 Einigungsgebühr aus Wert (5.000 +2.000 =7.000 €).

Das ganze geht auch komplizierter, wenn mehrere Verfahren oder außergerichtliche Sachen miterledigt werden: (Instruktiv hierzu...https://www.iww.de/rvgprof/archiv/einigungsgebuehr-so-rechnen-sie-gesamtvergleiche-richtig-ab-f22405).

**Comment by an-mus** [comment]
Hi,
ich hab die Einigungsgebühr jetzt auch noch mal bei den frei verfügbaren Gebühren eingefügt. Macht es Sinn, da alle andern Gebühren auch doppelt einzufügen?

**Comment by j-dimension** [comment]
@Mucki526 was meinst Du?

**Comment by an-mus** [comment]
Ich gehe mal davon aus, dass sich das Ticket erledigt hat. Zumindest kann die Beispielrechnung so im RVG Plugin gerechnet werden. Schwierig sind die Anrechnungsvorschriften. Ich glaube das ist nicht sinnvoll in Software abbildbar. 
Ich würde daher das Ticket schließen, bin aber für weitere Vorschläge offen.
