### ISSUE TITLE
Prozesskostenhilfe

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#48]
Die Auswahl der Prozesskostenhilfe am Ende der Berechnung und der Ausweis des Gesamtnettobetrags den einem die Staatskasse nicht vergütet (außer man erhält über Ratenzahlung vom Mandanten die Regelgebühren) macht so imhO nicht wirklich Sinn. Wenn man die Berechnung nutzen wollte, um das Formular HKR 120a (Vergütungsantrag an die Staatskasse) damit auszufüllen, müsste die Regelgebühr für jeden Gebührentatbestand neben der Prozesskostenhilfegebühr ausgewiesen werden. Eine Idee wäre es, wenn das Formular HKR 120a direkt befüllt werden dürfte. Das Formular ist aber ziemlich schlecht "programmiert" und dessen Verwendung Vorschrift (weil den Behörden heilig). Aber wie gesagt, zumindest, um die Berechnung ins Formular übernehmen zu können wäre die Anlehnung der Darstellung an das Formular hilfreich

**Comment by Mucki526** [comment]
Am besten Du schaust Dir mal das HKR120a an..... Die Idee wäre ja dass die Berechnung irgendwann einfach ins Formular eingetragen wird aus dem RVG-Rechner....  (Weil Questionlabel aber keine konkrete Frage von Dir hier ist).

**Comment by an-mus** [comment]
siehe auch hier: https://github.com/jlawyerorg/j-lawyer-org/issues/37

**Comment by an-mus** [comment]
Die Idee dahinter war, schnell den Anrechnungsbetrag nach § 58 Abs. 2 RVG ausgeworfen zu bekommen. Und auch nur zur Information. Das ganze wird ja auch nicht in den export übernommen.
Da ich jetzt auch Rechenfehler gefunden hab, würde ich den Punkt in der nächsten Version erstmal  rausnehmen.
