### ISSUE TITLE
RVG Rechner: bisherige Zahlungen brutto/netto

### ISSUE THREAD

**Issue by christianschneiderj** [jlawyerorg/j-lawyer-calculations#50]
Hallo,

wir hatten eben folgendes Szenario einer Mandantschaft mit Vorsteuerabzugsberechtigung in einer Verkehrsunfallsache.

Unsere Kosten sollten nun gegenüber der gegnerischen Versicherung mitgeteilt werden. Es gab auch bereits eine Teilzahlung auf Rechtsanwaltskosten von der gegnerischen Versicherung die auch als „bisherige Zahlung“ in der Rechnung berücksichtigt werden sollte.

Diese Kosten wurden aber in Kenntnis der Vorsteuerabzugsberechtigung unserer Mandantschaft von der gegnerischen Versicherung netto gezahlt.

Derzeit bietet der RVG-Rechner die Möglichkeit bisherige Zahlungen „brutto“ zu berücksichtigen. Besteht die Möglichkeit dieses Plugin noch um ein Feld „bisherige Zahlungen (Netto)“ zu ergänzen?

Bei Verkehrsunfallsachen dürfte der Fall gar nicht so selten eintreten, wenn Mandanten vorsteuerabzugsberechtigt sind und Teilzahlungen von RA-Kosten durch Gegner ohne Umsatzsteuer erfolgt.

Beste Grüße

Christian

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?topic=rvg-rechner-bisherige-zahlungen-brutto-netto

**Comment by an-mus** [comment]
@christianschneiderj 
Hallo Christian,
möglicherweise ist nur die Beschriftung im Programm nicht richtig. Wenn du in dem von dir beschriebenen Fall den Haken bei „Umsatzsteuer VV7008“ wegnimmst, dann erfolgt die gesamte weitere Rechnung ohne Umsatzsteuer und es wird auch in der Rechnung keine Umsatzsteuer auf die Vorauszahlung ausgeworfen. Damit müsste in deinem Fall die Rechnung an den Gegner korrekt sein.
Wenn du deinem Mandanten dann eine Rechnung über die übrige Umsatzsteuer stellen willst, machst du wieder den Haken bei „Umsatzsteuer VV7008“ und trägst die Zahlung des Gegners als Vorauszahlung ein. Der Rechnungsbetrag ist dann die Umsatzsteuer auf den Gesamtbetrag.
Ich meine dass es dann auch korrekt ist, dass die Rechnung dann die Umsatzsteuer auf die Vorauszahlung auswirft. Ich denke du musst sowohl auf die Zahlung des Gegners als auch auf die Zahlung des Mandanten je 19% abführen und nicht die Zahlung des Mandanten vollständig abführen.
So waren zumindest meine Gedanken.
Abgesehen wr die enthaltene Umsatzsteuer nicht richtig berechnet (Bug #51). Das ist aber jetzt korrigiert.
Sag doch mal Bescheid, ob das eure Anwendungsfälle umfasst.

Schöne Grüße
Anatol

**Comment by christianschneiderj** [comment]
Hallo,

ich glaube das trifft unser Problem noch nicht so ganz - oder wir reden komplett aneinander vorbei.

Ich mache mal folgenden konkreten Sachverhalt. Vorsteuerabzugsberechtigte Firma X-GmbH ist in einen Verkehrsunfall verwickelt. Firmenfahrzeug wird beschädigt. Haftung Gegner 100% unstreitig. Fahrzeugschaden nach Reparaturkostenrechnung 1.190,00 € (inkl. Umsatzsteuer). Nebenforderungen Unkostenpauschale und so Sachen lassen wir mal außen vor.

Ich habe also einen Schaden bei X-GmbH in Höhe von 1.000,00 € aus der Reparaturkostenrechnung.

Mein Anspruchschreiben an den Gegner lautet also wie folgt:

„Zahlen Sie bis in zwei Wochen den Schaden in Gestalt der Reparaturkosten, zuzüglich der durch unsere Beauftragung entstandenen Rechtsanwaltskosten, die sich wie folgt berechnen:

**Berechnung 1**
[berechnung_1.pdf](https://github.com/jlawyerorg/j-lawyer-calculations/files/2899852/berechnung_1.pdf)

Abschließend weisen wir darauf hin, dass unsere Mandantschaft vorsteuerabzugsberechtigt ist, somit ein Schaden in Gestalt der jeweils angefallenen Umsatzsteuer nicht besteht. Für den Zahlungseingang in Höhe von insgesamt 1.124,00 € haben wir uns den Tag X vorgemerkt.“

Mit der Methode Haken bei Umsatzsteuer herausnehmen, kann ich bei Mitteilung des Schadensersatzes RA-Kosten tatsächlich auch wie folgt ausgeben:

**Berechnung 2**
[berechnung_2.pdf](https://github.com/jlawyerorg/j-lawyer-calculations/files/2899855/berechnung_2.pdf)

Mein eigentliches „Problem“ kommt aber erst danach.

Gegner hat jetzt 1.124,00 € an mich gezahlt. 1000,00 € sind an Mandantschaft ausgezahlt ich habe jetzt die 124,00 € noch als Gebühren netto in der Akte. Umsatzsteuer will ich jetzt noch von der Mandantschaft holen. 

Also teile ich nach Abschluss der Angelegenheit meine Kosten wie folgt mit:

**Berechnung 3**
[berechnung_3.pdf](https://github.com/jlawyerorg/j-lawyer-calculations/files/2899856/berechnung_3.pdf)

Im Ergebnis müssen wir 23,56 € Umsatzsteuer abführen, das  ist genau der Betrag der auch bei Zahlbetrag gegenüber der Mandantschaft ausgeworfen wird. In der bisherigen Zahlung 124,00 € ist aber keine Umsatzsteuer enthalten.

Wenn ich jetzt Umsatzsteuer auf die 124,00 € (in Höhe von 19,80 €) und auf die Zahlung der Mandantschaft von 23,56 € (19% = 4,48 €) abführe, entspricht das einem Betrag in Höhe von 24,28 € (19,80 €+4,48 €). So viel sollte es aber nicht sein, da aus den Gebühren nur 23,56 € Umsatzsteuer angefallen sind. 

Für die Buchhaltung der Mandantschaft könnte die Kostennote auch verwirrend sein. Unsere Lösung wäre, dass wir in diesen Fällen einfach die Zeile unter den bisherigen Zahlungen „darin enthaltene MwSt“ einfach löschen.


**Zweiter Anwendungsfall, welchen unsere Kollegin beschrieben hat:**

Hier mal noch ein kurzes Beispiel, warum ein Feld Abzug vom Netto erforderlich/praktisch wäre:
Bei Mandanten mit Vorsteuerabzugsberechtigung werden Zahlungen auf unsere Kosten immer netto von Rechtsschutzversicherungen oder Gegnern erstattet.
Rechenbeispiel:
Unsere Kosten Netto:	1000,00 €
Mwst.			119,00 €
Erstattung Netto	500,00 €

D.h. Mandant muss noch 500,00 € netto und 119,00 € Mwst. selbst tragen. 
Für Buchhaltung und Finanzamt muss der Mwst.-Betrag in voller Höhe ausgewiesen werden.

LG Christian

**Comment by an-mus** [comment]
@christianschneiderj
Hi Christian,
ich habe das jetzt so gelöst, dass die Zeile mit der Umsatzsteuer aus der Vorauszahlung ausgeblendet werden kann. Ich hoffe ihr könnt damit eure Berechnungen erstellen. Wenn nicht, sag noch mal Bescheid
Ansonsten ist die Rechnung bisher korrekt. Du hast in deiner Rechnung den selben Fehler drin, wie wir vorher (Bug #51). In 23,56 € sind 3,76€ MwSt enthalten (nicht 4,48€). Plus die 19,80€ sind wir wieder bei 23,56€.
An
