### ISSUE TITLE
RVG-Rechner: enthaltende Umsatzsteuer in bisherigen Zahlungen (brutto) bug?

### ISSUE THREAD

**Issue by christianschneiderj** [jlawyerorg/j-lawyer-calculations#51]
Folgendes ist einer Mitarbeiterin von uns aufgefallen (mir selbst hätte niemals darauf geachtet):

Wir hatten bei einer Berechnung eine Teilzahlung (brutto) die auch berücksichtigt wurde:

als bisherige Zahlung wurde ein Betrag von 201,71 € eingetragen. Sodann wird bei "darin enthaltende Umsatzsteuer" von dem Plugin 38,32 € ausgegeben, was unserer Ansicht nach falsch ist.

Bei dem Brutto-Betrag handelt es sich um folgende Gebühren:
1,3 Gebühr aus 1.340,10 €: 149,50 €
Post und Telekomm: 20,00 €
Zwischensumme: 169,50 €
hieraus 19% Umsatzsteuer: 32,21 €
gesamt: 201,71 €

in dem Betrag von 201,71 € ist also eine Umsatzsteuer in Höhe von 32,21 € enthalten und nicht 38,21 €.

Das Plugin berechnet offensichtlich die enthaltene Umsatzsteuer mit Ausgangswert * 0,19. 

M.E. müsste - da im Ausgangswert die Umsatzsteuer bereits enthalten ist - die Formel lauten: enthaltende Umsatzsteuer = "bisherige Zahlung Brutto" / 1,19 * 0,19
![screenshot_bisherige_zahlungen](https://user-images.githubusercontent.com/47816329/53093421-aaf1bd00-3517-11e9-842c-868144133d6a.png)

**Comment by j-dimension** [comment]
Das hört sich für mich absolut plausibel an. @an-mus, okay wenn ich das anpasse?

**Comment by an-mus** [comment]
Ich sehe das auch so, dass da ein Rechenfehler ist. Ich könnte das heute Abend ändern. Wenn du jetzt dran bist, mach das ruhig.

**Comment by j-dimension** [comment]
Ich habe eben Version 1.9.2 des RVG-Plugins veröffentlicht. @an-mus und @christianschneiderj - bitte gern mal drüberschauen (vorher die Version verifizieren - wird im Fenstertitel angezeigt).
