### ISSUE TITLE
RVG-Tabelle - "Grenzwerte"

### ISSUE THREAD

**Issue by sigiberlin** [jlawyerorg/j-lawyer-calculations#52]
Hi"

wenn ich den Code in  j-lawyer-calculations/src/1.9.1/RvgTablesRangeList.groovy richtig verstehe, dann sucht die Funktion das erste Vorkommen des Streitwertes in den Ranges.

was, wenn der Streitwert genau 500 (oder 1000, 1500 ...) ist? welche Gebühr wird dann gefunden? Wäre es nicht sinnvoller (und sicherer), den Beginn des jeweiligen Ranges auf xxx,01 zu setzen?

**Comment by sigiberlin** [comment]
ups sorry, versehentlich geschlossen...

**Comment by j-dimension** [comment]
@sigiberlin schau mal in 
https://github.com/jlawyerorg/j-lawyer-calculations/blob/master/src/1.9.1/RvgTablesRange.groovy

Dort ist die "contains"-Methode wie folgt implementiert:

boolean contains(float number) {
    (number > low && number <= high)
}

D.h. bei einem Bereich von 500 bis 1000 wäre eine 500 NICHT enthalten, eine 1000 wäre aber enthalten.

Passt so?
