### ISSUE TITLE
Zeithonorarplugin - Minutengenau Abrechnung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#54]
Endlich ist es da, das plugin für Zeithonorar. Aber der Teiler ist ungünstig. Minuteneinstellung wäre besser als Dezimalteiler 50 min sind im Plugin 0,8333... besser wäre einfach 50 min.

**Comment by j-dimension** [comment]
Von @an-mus nun umgesetzt: 
https://github.com/jlawyerorg/j-lawyer-calculations/commit/df8a97c005715f40e4fc2cc2f02266dc63c8230a
