### ISSUE TITLE
Gerichtskostenvorschuss

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#59]
Der RVG Rechner bietet an, einen Gerichtskostenvorschuss zu Rechnung hinzu zu nehmen. Dieser wird dann dummerweise mit 19% Umsatzsteuer belegt. Das darf nicht sein. Gerichtskosten sind immer umsatzsteuerfrei.

**Comment by an-mus** [comment]
Du hast natürlich recht. Danke für den Hinweis. Die Lösung wird sein, dass für alle sonstigen Gebühren unterschieden wird, ob sie Umsatzsteuerpflichtig sind oder nicht. Das ermöglicht dann auch beliebig viele Umsatzsteuerfreie Auslagen aufzuführen (#42). 
Der Patch ist im groben fertig, braucht aber noch etwas feinschliff, da die Umbauten im Code doch etwas umfangreicher sind. 
Schöne Grüße

**Comment by an-mus** [comment]
in  e12d60b  geschlossen. Bei den benutzerdefinierten Einträgen wird jetzt unterschieden, ob Umsatzsteuer anfällt oder nicht. Geändert in allen Plugins.
