### ISSUE TITLE
Rechner Strafrecht: Aktenversendungspauschale mit USt

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#61]
Ein Anwender per Email:

> anbei übersende ich Dir eine Entscheidung, die ich richtig finde und auch so abrechne. In Deinem Kostenrechnerprogramm ist die Aktenversendungspauschale aber ohne Umsatzsteuer angelegt. Du kannst diese Entscheidung ja an den "Erfinder" der Berechnungsprogramms weiterleiten. Er kann mich natürlich auch anrufen, wenn er dazu noch etwas wissen oder besprechen will, oder Du natürlich auch. 

Dokument anbei.
[AG Giessen, Urteil v 10.08.2018 - 41 C 17918 - Aktenversendungpauschale und USt.pdf](https://github.com/jlawyerorg/j-lawyer-calculations/files/3432978/AG.Giessen.Urteil.v.10.08.2018.-.41.C.17918.-.Aktenversendungpauschale.und.USt.pdf)

**Comment by an-mus** [comment]
Du hast Recht und ich habs geändert. Selbst der BGH hat das bei nem Streitwert von 2€ irgendwas schon mal entschieden.
