### ISSUE TITLE
Plugin Strafrecht und Pflichtverteidigung zusammenlegen

### ISSUE THREAD

**Issue by an-mus** [jlawyerorg/j-lawyer-calculations#62]
Für meinen Geschmack wird die Liste der Plugins mittlerweile etwas lang und unübersichtlich. Da sich die Plugins für Starfverfahren und für die Pflichtverteidigung sehr ähnlich sind (sowohl sachlich, als auch der Code) würde es sich anbieten, beide zusammenzulegen. 
Auch im Hinblick auf das Plugin für das Bußgeldverfahren, da ja auch dort zwischen Wahl- und Pflichtverteidigung unterschieden wird und dann auch wieder zwei Plugins nötig wären.

**Comment by j-dimension** [comment]
@j-dimension
