### ISSUE TITLE
Travis CI is broken as oraclejdk8 is no longer part of Xenial

### ISSUE THREAD

**Issue by Oliver-Loeffler** [jlawyerorg/j-lawyer-calculations#63]
Please use dist: trusty in order to get the CI again working.

**Comment by j-dimension** [comment]
Ouch, you are totally right. Two failed builds in the last four days but no email notification :-(

Thanks, @Oliver-Loeffler !

**Comment by j-dimension** [comment]
Travis CI build turned to green again. Thx!
