### ISSUE TITLE
Bereits bezahlt

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#65]
Es gibt die Möglichkeit, einen Kostenvorschuss als bereits bezahlt in die Schlussrechnung einzutragen und man kann entscheiden, ob dieser Umsatzsteuer enthält oder nicht. Das greift IMHO aus zwei Gründen zu kurz. Zum einen kann es sein, dass mehrere Kostenvorschussnoten gestellt und bezahlt wurden oder mehrere Raten bezahlt wurden. Zum anderen wird ein einer Kostenvorschussnote (zumindest bei uns) sowohl Honorare (ggf. mit 19% USt, wenn Mandant in Deutschland lebt) und in der selben Rechnung umsatzsteuerfreie Gerichtskosten angefordert. Man muss als angegeben können bei einer Zahlung, welcher Teilbetrag mit und welcher ohne Umsatzsteuer in Abzug zu bringen ist. Das sollte sich für eine Steuerprüfung dann auch nachvollziehen lassen, d.h. es sollte auch möglich sein, das Datum der Zahlung / Teilzahlung zu erfassen. Wird man, wenn es einmal ein Buchführungsmodul oder zumindest elektronisches Kostenblatt hat sowieso benötigen....

**Comment by an-mus** [comment]
Ich würde steuerfreie Vorschüsse versuchen, in die Plugins einzubeziehen. Die Erfassung der einzelnen Zahlungen hängt aber davon ab, wann die Buchführung in j-lawyer integriert ist.
