### ISSUE TITLE
Strafrechtsplugin: Erledigungsgebühr

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#66]
Ein Anwender meinte heute zu mir: die Erledigungsgebühr sollte / muss in allen "Instanzen" möglich sein. Ich selbst kann das nicht bewerten.

**Comment by an-mus** [comment]
Ja, das stimmt für das RVG und das Sozialrechtsplugin. Im Strafrecht gibt es die Erledigung nur, wenn eine Hauptverhandlung vermieden wird, also nur im Vorverfahren. Das ist aber mittlerweile so in den drei Plugins umgesetzt. 
Es ist aber nicht ausgeschlossen, dass ich noch was übersehen habe, bzw. Ergänzungen sinnvoll sind. Wenn du magst kannst du gerne meine e-Mail Adresse weitergeben, um das direkt zu klären. 
Grüße

**Comment by j-dimension** [comment]
Danke Dir! Deine Mailadresse habe ich weitergereicht. Vorher bekam ich noch folgende Information:

> IV. Zusätzliche Gebühren
> 
> Nach Nr. 4141 VV RVG erhalten Sie eine sog. „Befriedungsgebühr“ in Höhe der Verfahrensgebühr (bei amtsgerichtlichen Verfahren z.B. wie Nr. 4106 VV RVG), wenn durch Ihre anwaltliche Mitwirkung das Verfahren eingestellt oder die Hauptverhandlung entbehrlich wird.
> 
> Der Gesetzgeber wollte Anreize für die außergerichtliche Streitbeilegung schaffen, was der Entlastung der Gerichte dienen sollte. Er hat im Vergütungsverzeichnis abschließend vier Varianten aufgezählt, durch die Sie als Rechtsanwalt belohnt werden:
> 
> 1. Strafverfahren nicht nur vorläufig eingestellt
> 
> Zum einen entsteht die Gebühr, wenn das Strafverfahren nicht nur vorläufig eingestellt wird. Hierzu kann es schon im vorbereitenden Verfahren vor der Strafverfolgungsbehörde kommen oder  💪im gerichtlichen Verfahren oder auch erst im Berufungs- oder Revisionsverfahren. Wird die Strafsache in der Hauptverhandlung eingestellt, so fällt Nr. 4141 VV RVG nicht zusätzlich neben der Terminsgebühr an.
> 
> 2. Hauptverfahren nicht eröffnet
> 
> Absatz 1 Nr. 2 VV RVG sieht vor, dass Sie die Zusatzgebühr auch dazu verdienen können, wenn das Gericht beschließt, das Hauptverfahren nicht zu eröffnen.
> 
> 3. Rücknahme von Einspruch, Berufung, Revision
> 
> Darüber hinaus werden Sie gebührentechnisch bevorzugt, wenn sich das gerichtliche Verfahren durch Rücknahme des Einspruchs gegen den Strafbefehl, der Berufung oder der Revision des Angeklagten oder eines anderen Verfahrensbeteiligten erledigt.
> 
> Wenn bereits ein Termin zur Hauptverhandlung bestimmt ist, entsteht die Gebühr nur, wenn der Einspruch, die Berufung oder die Revision früher als zwei Wochen vor Beginn des Tages, der für die Hauptverhandlung vorgesehen war, zurückgenommen wird (Nr. 3).
> 
> 4. Ende durch Beschluss
> 
> Auch wenn das Verfahren durch Beschluss nach § 411 Abs. 1 Satz 3 StPO endet, entsteht die Gebühr.
> 
> Die Gebühr nach Nr. 4141 Abs. 1 VV RVG entsteht nicht, wenn eine auf die Förderung des Verfahrens gerichtete Tätigkeit nicht ersichtlich ist.

**Comment by an-mus** [comment]
Die Gebühr fällt nur einmal an, aber je nach Instanz in verschiedener Höhe. Wird im neuen Strafrechts/Bußgeld Plugin korrigiert. Siehe #62

**Comment by j-dimension** [comment]
@an-mus Danke Dir! D.h. wir können dieses Ticket hier schliessen?
