### ISSUE TITLE
Betreuervergütung

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#68]
von einem Anwender: 

was müsste gemacht werden, damit die Betreuervergütung mit der Software erstellt werden kann?! Man müsste ja nur die neuen Vergütungen seit diesem Jahr berücksichtigen (was wesentlich einfacher ist, als davor). Könnte ich als Nichtprogrammierer hierzu etwas beitragen, dass solch eine Umsetzung vorgenommen werden kann?

**Comment by j-dimension** [comment]
weitere Information des Anwenders:

die genaue Vergütung kann hier entnommen werden:
 
https://www.bundesanzeiger-verlag.de/betreuung/wiki/Betreuervergütung_2019
 
Die Tabelle sieht komplizierter aus, als Sie ist. Aktuell rechnet man noch den alten und neuen Vorgaben ab, dass ist etwas kompliziert. Wenn man jetzt noch zwei Monate wartet, gibt es nur noch die Rechnungen nach den Vorgaben aus dem obigen Link, dass ist wirkich deutlich einfacher.
 
Ausschlaggebend ist immer wie lange die Betreuung besteht:
 
1-3       Monat
4-6       Monat
7-12     Monat
13-24 Monat
 
Dann muss geguckt werden, wo der Betroffene wohnt "zu Hause" oder "besondere Wohnform".
 
Der letzte Punkt wäre dann noch
 
"vermögend" und "unvermögend"
 
Das Gericht rechnet rechnet immer mit 30 Tagen.
 
Je nach Ausbildung des Betreuers, kann er die Vergütungstabelle 1-3 in Anspruch nehmen. 
 
1. ohne besondere Kenntnisse 
2. Mit berufsbezogener Ausbildung
3. Mit Hochschulstudium
 
 
Die Abrechnung beginnt immer einen Tag nach Bekanntgabe:
 
Um es mal einfach zu halten, mache ich das jetzt mal ohne soforte Anordnung usw:
 
Der Beschluss datiert vom 01.09.2019 und wurde mir am selben Tag zugestellt:
 
Betreuungsbeginn = (Das Datum muss der Betreuer in der Software beim Klienten einmal hinterlegen)
 
Abrechnungsbeginn = Das hinterlegte Datum + 1 Tag
 
Abrechnungszeitrum hier wäre also 02.09.2019 bis 01.12.2019
 
Wire gehen jetzt davon aus, dass der Betreute mal unvermögend ist und Frau XXX die Betreuung hat und der Betroffene im Pflegeheim (besondere Wohnform) lebt.
 
Würden als in den ersten 3 Monaten, je Monat 317,00 € anfallen. 
 
317,00 € * 3 = 951,00 €
 
Also kein Hexenwerk.
 
Die Software sollte durch Eingabe des Betreuungsbeginns und auch Betreuungsende erkennen, in welchen Abrechnungsquartal man sich befindet. 
 
Gerne stelle ich Ihnen mal Rechnungen zur Verfügung, würde aber gerne warten, bis diese ausschließlich auf der neuen Tabelle beruhen.
 
Unter https://kbetreuungsmanager.knetsoft.de
 
können Sie sich mal die aktuelle Software runterladen und sich das ansehen. Ist bis 10 Klienten kostenlos, ohne Einschränkungen.

**Comment by j-dimension** [comment]
Eingangsdaten sind noch:

- tag des ersten beschlusses 
- tag der eigenen betreuerbestellung (liegt danach)

zeitraum beginnt mit tag des ersten beschlusses plus 1 tag

betreuung wird immer quartalsweise abgerechnet

**Comment by j-dimension** [comment]
szenario 1: kein vorbetreuer, ganz neuer fall - zeitraum beginnt 1 tag nach bestellung
--> bspw. 01.04. bis 1.7. erstes betreuungsquartal


szenario vorbetreuer: 
hatte schon lange betreuuer
--> beginnt bspw. 13. quartal

**Comment by j-dimension** [comment]
wenn betreuung endet, (tag der aufhebung des beschlusses) , dann teilt man den monatlichen betrag durch 30 * anzahl tage (annahme ist also, dass alle monate mit 30 tagen gerechnet werden)

wenn über 150K vermögen oder gewerbe, dann extravergütung

**Comment by an-mus** [comment]
@j-dimension: ich bin übrigens an dem Plugin für Betreuervergütung dran. Nicht dass wir doppelt arbeiten :-)
Sag bescheid wenn du noch weitere Überlegungen dazu hast

**Comment by j-dimension** [comment]
@an-mus Oh wow, das wusste ich nicht - hatte tatsächlich vor in der übernächsten Woche daran zu arbeiten, allerdings noch nicht mit der Berechnung, sondern einem Falldatenblatt zur Erfassung der Stammdaten. 
Das würde sich also prima ergänzen!

**Comment by an-mus** [comment]
So, die Funktion ist als Falldatenblatt umgesetzt. Da ist sie besser aufgehoben, weil die Berechnung auf fixen, Aktenspezifischen Daten beruht. 
Das Falldatenblatt wird mit der Version 1.12. verfügbar sein. 
Bug Reports gerne hier hin: https://github.com/jlawyerorg/j-lawyer-forms/issues
