### ISSUE TITLE
Gerichtskosteneinstellung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#69]
Wenn man im RVG-Modul mit den Pfeilen von 3 auf 2 Gebühren Vorschuss bei den Gerichtskosten geht, kommt bei der Erzeugung der Rechnung in der eingefügten Tabelle bei den Gerichtskosten eine 1,999999 statt einer 2.

**Comment by j-dimension** [comment]
Wie heisst der Wert in der Oberfläche, den Du von 3 auf 2 änderst?
Welche Position in der Ergebnistabelle zeigt dann die 1,999999?
Übernimmst Du das Ergebnis per Copy & Paste oder lässt Du es direkt über einen Platzhalter einfügen?

Ich bekomme das gerade nicht hin.

**Comment by an-mus** [comment]
Da war tatsächlich ein Fehler in der Formatierung.
