### ISSUE TITLE
Mehrvergleiche im RVG plugin

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#72]
Vielleicht bin ich zu vorschnell,
aber auf Anhieb konnte ich nicht erkennen, dass die Abrechnung von Mehrvergleichen im RVG Rechner ohne Weiteres möglich ist (also vielleicht auf Umwegen).
Nachdem in der 1.11 wohl die Übernahme der Berechnung richtig gut aussehen wird, wäre der Ausbau des Plugins auch auf solche Neben- und Sonderfälle richtig gut.

**Comment by an-mus** [comment]
Über die zweite Zeile der sonstigen Gebühren können beliebig viele weiter wertgebühren hinzugefügt werden. Die Eingungsgebühr ist da schon mit bei. Streitwert und Gebühr können beliebig angepasst werden. Die Deckelungen bei Mehrvergleichen muss man wohl weiterhin per Hand rechnen. Ich hab zumindest keine Idee, wie man das universell in Software abbildbar macht.
Ich würde aber das Plugin dahingehend ändern, dass der Betrag unter den "sonstigen" Rahmengebühren manuell veränderbar ist. Dann kann man die gedeckelte Einigungsgebühr dort eintragen.
Oder hast du noch mehr Ideen?

**Comment by Maz111111** [comment]
Sorry, dass ich nicht geantwortet habe. Ich hatte meine Mailbenachrichtigung falsch eingestellt und nichts mitbekommen (natürlich auch nicht mal von selbst nachgeschaut).

Also meine Idee wäre, im Rechenbereich für die gerichtlichen Abrechnungen jeweils ein weiteres Feld Verfahrensgebühr und Einigungsgebühr aus Mehrwert einzufügen. Der Quotient mit 0,8 und 1,5 wäre klar und sollte vorgegeben sein. Der jeweilige Mehrwert muss - da er unterschiedlich sein kann - sowohl für die (Mehr-) Verfahrensgebühr als auch für die (Mehr-) Einigungsgebühr von Hand eingegeben werden.
Das Feld kann nur angewählt werden, wenn im jeweiligen "normalen" Verfahrens- oder Einigungsfeld etwas steht bzw. dieses angewählt ist.
Wird das jeweilige Mehrwertfeld angewählt und ausgefüllt, sollte das Plugin von selbst die Werte aus dem jeweiligen "Normalfeld" und dem jeweiligen "Mehrwertfeld" zusammenrechnen und bestimmen, ob entweder die Deckelung greift (und diese dann auch in die Berechnung übernehmen) oder ob die beiden einzelnen Gebühren anzusetzen sind, da kleiner/gleich der Deckelung sind.

Ich kann Dir gern eine Mehrvergleichsabrechnung von mir als Vorlage zur Verfügung stellen. Nur programmieren kann ich es leider nicht.

Die Mails von Github rufe ich meistens nur Di - Do ab.

**Comment by an-mus** [comment]
An der Baustelle ist es schon weitergegangen :-)
siehe unter Bugreport #133.
Die Anrechnungsbeträge nach § 15 Abs. 3 werden jetzt jeweils für Verfahrens und Einigungsgebühr ausgegeben. Die Frage, ob die Deckelung greift und welcher Betrag angerechnet wird, sollte das Plugin sebstständig berechnen.
Ich würde mich aber sehr über Tests und Rückmeldung freuen, ob es funktioniert wie gewünscht.
Schöne Grüße.
