### ISSUE TITLE
Fehlender reduzierter Mehrwertsteuersatz

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#77]
Fähren und andere ÖPNV haben (z.B. in Konstanz) manchmal einen reduzierten Umsatzsteuersatz, also nicht 0% oder 19% sondern - 7% fehlt im RVG-Rechner.

**Comment by an-mus** [comment]
siehe #30.
Vgl. KG Berlin: https://www.burhoff.de/asp_weitere_beschluesse/inhalte/2348.htm
