### ISSUE TITLE
Streitwertdeckelung fehlt (Abnahme Vermögensauskunft)

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#80]
Die Gebühren und zugehörige Streitwertdeckelung auf 2000 € für Antrag auf Abnahme einer Vermögensauskunft in der Zwangsvollstreckung fehlt.

**Comment by an-mus** [comment]
Ich habe die Gebühren für die Zwangsvollstreckung und die Zwangsversteigerung hinzugefügt. Finden sich unter den sonstigen Wertgebühren.

**Comment by an-mus** [comment]
siehe #84
