### ISSUE TITLE
Anrechnung Beratungshilfe bei VKH Abrechnung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#85]
erklärt sich von selbst.
Könnte ich aktuell nur mit "bisherige Zahlungen" abbilden. Dann müsste ich es aber zum einen brutto angeben und es wäre in der Abrechnung nicht eindeutig identifizierbar.

**Comment by an-mus** [comment]
Ich hab noch ein Frage, wie wir das am schlausten umsetzen. Ich denke die Anrechnung gehört unter den Punkt "anrechenbarer Teil" in der Bererchnung der ersten Instanz. Die aktuelle Berechnung geht davon aus, dass im Vorverfahren normale RVG Gebühren angefallen sind. Ich denke, dass man nicht davon ausgehen kann, dass in allen gerichtlichen Verfahren, in denen PKH gewährt wurde, es im Vorverfahren Beratungshilfe gab (alleine weil es nicht in allen Bundesländern Beratungshilfe gibt). Ich würde die Berechnung deshalb nicht dahingehend ändern, dass wenn Prozesskostenhilfe ausgewählt wurde automatisch immer eine halbe 2503 Gebühr angerechnet wird.
Ich könnte mir als Lösung vorstellen, das Feld für den Betrag der Anrechnung editierbar zu machen. Das Plugin würde dann immer eine 0,65 Gebür vorschlagen. Der Anrechnungsbetrag könnte aber manuell überschrieben werden (mit einer halben Beratungshilfegebühr).
Wäre das eine gute Lösung?

**Comment by Maz111111** [comment]
Sorry, dass ich nie geantwortet habe. Die Benachrichtigungsmails gingen damals noch in den Spam und ich wusste gar nicht dass es solche Mails überhaupt gibt.
Es wäre irgendwie schöner wenn man ein zusätzliches Feld / Zeile hätte "abzgl. anzurechnender Beratungshilfe in Höhe von "edit"", welches man mit einer Checkbox ein und ausschalten könnte.
Herzliche Grüße

**Comment by Maz111111** [comment]
Hab noch weiter überlegt:
eigentlich müssten nur zwei neue Zeilen rein:
"abzgl. anzurechnender Beratungshilfe in Höhe von 35,00 EUR
und
"abzgl. anzurechnender Beratungshilfe in Höhe von 42,50 EUR",
beides jeweils zum Anhaken und wird dann als Zeile in die Berechnung eingefügt und netto entsprechend in der Rechnung abgezogen.
Vielleicht kannst Du ja nochmals drüberschauen und die Idee umsetzen
Herzliche Grüße
Martin
