### ISSUE TITLE
Verringerter Umsatzsteuersatz 7%

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#86]
Bei der Abrechnung mit dem Mandanten muss man oft Fähre/Zug/Bustickets abrechnen. Manche Tickets des ÖPNV haben 0% Umsatzsteuersatz, manche Verkehrsmittel 7% Umsatzsteuersatz. Das müsste man bei der jeweiligen Position auswählen können (und ggf. auswählen, ob die eingegebene Zahl das Brutto oder das Netto ist).

**Comment by an-mus** [comment]
Ist kein Bug. siehe #77 und #30
