### ISSUE TITLE
Eingabedaten

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#88]
Bei umfangreicheren Rechnungen kommt es vor, dass man die eine oder andere Postion vergisst. Es wäre hilfreicht, wenn man dann nicht wieder alles von 0 an eingeben müsste in den RVG Rechner, also z.B. entweder letzte Berechnungen nochmals einfügen aus Pulldownliste oder evt. einfach die letzte Berechnung eingefügt lassen und einen Button für Reset bei Neuberechnung.

**Comment by j-dimension** [comment]
Das ist eher keine Aufgabe der Plugins, wäre vielmehr Teil der Finanzen-Funktionalität.

**Comment by j-dimension** [comment]
Schliesse den hier, da er insgesamt in https://github.com/jlawyerorg/j-lawyer-org/issues/119 aufgehen sollte.
