### ISSUE TITLE
Erhöhungsgebühr separat

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-calculations#9]
Im Sozialrechts-Rechner (und vermutlich dem normalen auch) wird die Erhöhungsgebühr direkt in die Min/Max-Werte der Geschäfts/Verfahrensgebühr eingerechnet. Ich kenne es anders und finde es auch für mich und das Gegenüber selbsterklärender, wenn die Erhöhungsgebühr eigenständig ausgewiesen wird:

zb für drei Mdt:

VG VV3102: 300€
ErhG VV1008: 2×90€=180€

**Comment by j-dimension** [comment]
ErhG VV1008: 2×30% von 300€=180€

muß es natürlich heißen.

**Comment by j-dimension** [comment]
und für die Gebührenhöhe so Sachen wie

Mittelgebühr +30%
Mittelgebühr +20%
Mittelgebühr +10%
Mittelgebühr
Schwellengebühr
Mittelgebühr -10%
Mittelgebühr -20%

wobei das nur eine Berechnungshilfe sein sollte, deren Ergebnis man immer auch manuel überschreiben kann.

als Auswahlliste kenne ich von anderen Rechnern und das hilft IMHO auch weiter.

Und wenn man dann noch weitere Werte definieren könnte (weil regional unterschiedlich):

Verfahrensgebühr für:
UK
eR
Kostenklage / Kostenwiderspruch

**Comment by j-dimension** [comment]
https://www.j-lawyer.org/?p=2669#comments

**Comment by an-mus** [comment]
zum Thema "Erhöhungsbegühr" 1008:
ob man die Erhöhung in die Verfahrensgebühr extra ausweist oder in der Verahrensgebühr darstellt ist ein bisschen Geschmackssache. Beide Darstellungsweisen finden sich. Formell handelt es sich jedoch nicht um einen Gebührentatbestand, sondern um eine Erhöhung des Gebührensatzes der Verfahrensgebühr. Insofern ist es formell richtig, die Gebühr nicht extra auszuweisen. Im RVG Plugin ließe sich das als eigene Gebühr darstellen. Bei Rahmengebühren ist das schon nicht mehr möglich, da sich jeweils der Mindest- und der Höchstbetrag erhöhen. Dann den Anteil auszuweisen, der auf der Erhöhung nach 1008 beruht ist nicht möglich und sinnvoll. Da es der Systematik des RVG entspricht würde ich bei der bisherigen Darstellung bleiben und die Erhöhung nach RVG 1008 nicht separat ausweisen. -> wontfix

Die Möglichkeit, die Gebühren pauschal zu erhöhen und zu verringern wird es im Sozialrechtsplugin und im Strafrechtsplugin geben.

Die "Schwellengebühr" kommt, soweit ich das sehe, nur bei VV 2300 zum tragen. Dort ist eine Gebühr von 1,3 voreingestellt. Ob die Kriterien für eine Erhöhung erfüllt sind, ist eine rechtliche Frage. es kann dann eine höhere Gebühr über den Spinner eingestellt werden. 

Bei Verfahren des einstweiligen Rechtsschutzes handelt es sich um eigenständige Verfahren im Sinne des RVG, die auch separat abgerechnet werden sollten. Dazu kommt, dass in der Regel wohl ein anderer Streitwert angesetzt wird. Es sollte daher für jedes Verfahren eine eigene Rechnung erstellt werden -> wontfix

**Comment by j-dimension** [comment]
Alles schlüssig - vielen Dank!
