### ISSUE TITLE
Übernahme Gegenstandswert in RVG Berechnung

### ISSUE THREAD

**Issue by Maz111111** [jlawyerorg/j-lawyer-calculations#92]
Wenn im Reiter "Schäden" ein Gegenstandswert angegeben wird und dann über "neue Berechnung" das RVG Plugin genutzt wird, wird ein Punkt anstatt eines Kommas gesetzt.
Der RVG Rechner geht dann immer von einer Dezimalstelle zuviel aus.
Bsp:
Gegenstandswert 100,00 wird im RVG Rechner als Streitwert 100.0 übernommen, was dann in der Berechnung wiederum als 1000,00 interpretiert wird.

**Comment by PBaumfalk** [comment]
Auch der Bug ist ein bissel nervig. ;-)

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

Sent by Mobile
