### ISSUE TITLE
Formatierung Tabelle Zeitvergütung

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#95]
Bei mir wird bei Anlage einer Zeitabhängigen Vergütung mit dem Plugin immer die erste Spalte Links (mit der Zeit) umgebrochen und die min rutscht in die nächste Zeile. Die Spalte müsste etwas breiter sein oder vorkonfigurierbar...

**Comment by j-dimension** [comment]
Lichtgeschwindigkeit... vielen Dank, @an-mus !
