### ISSUE TITLE
Berechnungsplugin nach Erstellung eines Dokumentes geöffnet lassen

### ISSUE THREAD

**Issue by Mucki526** [jlawyerorg/j-lawyer-calculations#96]
Es kommt oft vor, dass ich bei der Erstellung von Rechnungen eine Postion oder Gebühr vergesse. Wenn ich dann zurück in den RVG-Rechner wechsle, stehen da meine kurz vorher mühseelig eingegebenen Werte nicht mehr, sobald ich ein Dokument (Kostennote) daraus erstellt habe. Also - entweder alles nochmal von vorne oder händisch nachbessern. Besser wäre doch (Vorschlag). Die letzte Eingabe bleibt erhalten, z.B. bis man den Client schließt oder sich abmeldet oder einfach dauerhaft. Es gibt einen Button, mit dem man alle Einträge auf den Ursprungswert setzt ("Quasi Werksreset"). Wenn man dann von der falschen Kostennote in den Rechner zurückwechselt, kann man den fehlenden falschen Wert kurz ergänzen und eine neue Version der Kostennote erzeugen (oder die alte überschreiben).

**Comment by j-dimension** [comment]
Das ist keine Aufgabe für die Plugins, sondern Teil einer umfassenden Umsetzung des Komplexes "Finanzen".

**Comment by an-mus** [comment]
@j-dimension In letzter Konsequenz ist das doch der Vorschlag, die RVG Plugins in Falldatenformulare umzuwandeln. Wäre aufwändig, aber möglich. Aber wäre das der richtige Weg?

**Comment by j-dimension** [comment]
Das wäre in der Tat eine Option. 

ABER: die Speicherung der Falldaten ist unter der Haube eine einfache Liste von Schlüssel-Wert-Paaren. Das würde bspw. aktenübergreifende Auswertungen erschweren / verhindern. Wenn das keine Anforderung ist, dann könnte man diesen Schritt gehen. Der Aufwand wäre m.E. sogar recht überschaubar.

**Comment by Dickmaulruessler** [comment]
> 
> 
> Das ist keine Aufgabe für die Plugins, sondern Teil einer umfassenden Umsetzung des Komplexes "Finanzen".

Ich kann das nicht überblicken, frage aber einfach noch einmal dumm nach. 
Bei **"Kopieren"** bleibt das Plugin-Fenster geöffnet und die Werte erhalten.
Bei **"Dokument erstellen"** schließt es sich und alles ist futsch...

Kann nicht nur das automatische Schließen des Plugin-Fensters unterbunden werden?

Das von https://github.com/Mucki526 beschriebene Problem teile ich grundsätzlich. Man vergisst häufiger mal was....

**Comment by j-dimension** [comment]
> Kann nicht nur das automatische Schließen des Plugin-Fensters unterbunden werden?

Das lässt sich natürlich sehr einfach machen. Nur das Speichern und beim nächsten Anwendungsstart wieder öffnen ist Teil des größeren Themenkomplexes.

**Comment by Dickmaulruessler** [comment]
Das würde das Problem glaube ich schon ausreichend lösen

**Comment by j-dimension** [comment]
erledigt
